packages/tools/release-utils-internal/bin/rui-release-widget-gh.ts, packages/tools/release-utils-internal/package.json, packages/tools/release-utils-internal/src/git.ts, packages/tools/release-utils-internal/src/github.ts, packages/tools/release-utils-internal/src/module-build.ts, packages/tools/release-utils-internal/src/mpk.ts, packages/tools/release-utils-internal/src/shell.ts, packages/tools/release-utils-internal/src/steps.ts, pnpm-lock.yaml
-   [ ] Bug fix
-   [ ] Feature
-   [x] Refactor
=> Uniform exec calls

packages/tools/release-utils-internal/package.json, packages/tools/release-utils-internal/src/mpk.ts, packages/tools/release-utils-internal/src/package-info.ts, packages/tools/release-utils-internal/src/package-xml.ts, packages/tools/release-utils-internal/src/shell.ts, packages/tools/release-utils-internal/src/steps.ts, packages/tools/release-utils-internal/utils.ts, pnpm-lock.yaml
- Add `cross-zip` package to allow charts build on windows runners
- Refactor package.xml utils
- Update type and add some helpers in `package-info`
=> Update mpk manipulation utils

.github/configs/labeler.yml
- Have label for each package in repo
- Labeler config
=> Update labeler config

packages/tools/release-utils-internal/src/monorepo.ts
-   [x] Bug fix
-   [ ] Feature
-   [ ] Refactor
- fix release utils on windows
- Remove single quotes as windows shell don't interprets them well
=> Fix: don't use single quotes in listPackages

packages/pluggableWidgets/barcode-scanner-web/CHANGELOG.md, packages/pluggableWidgets/barcode-scanner-web/package.json, packages/pluggableWidgets/barcode-scanner-web/src/components/__tests__/BarcodeScanner.spec.tsx, packages/pluggableWidgets/barcode-scanner-web/src/hooks/useCustomErrorMessage.ts, packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts, packages/pluggableWidgets/barcode-scanner-web/src/package.xml
-   Contains unit tests ✅
-   Contains breaking changes ❌
-   Contains Atlas changes ❌
-   Compatible with: 9️⃣
-   Did you update version and changelog? ✅
-   PR title properly formatted (`[XX-000]: description`)? ✅
-   [x] Bug fix
-   [ ] Feature
-   [ ] Refactor
- Fix issue with camera resource not disposed on unmount
- Now, we controlling stream explicitly to make sure it disposed after use
- add `stopAdyncDecode` coll to make sure we don't have setTimeout loops
=> [WC-1337]: Fix barcode-scanner

packages/pluggableWidgets/language-selector-web/CHANGELOG.md, packages/pluggableWidgets/language-selector-web/package.json, packages/pluggableWidgets/language-selector-web/src/components/LanguageSwitcher.tsx, packages/pluggableWidgets/language-selector-web/src/components/__tests__/__snapshots__/LanguageSwitcher.spec.tsx.snap, packages/pluggableWidgets/language-selector-web/src/package.xml, packages/pluggableWidgets/language-selector-web/src/ui/LanguageSelector.scss
-   Contains unit tests ❌
-   Contains breaking changes ❌
-   Contains Atlas changes ❌
-   Compatible with: MX 9️⃣
-   Did you update version and changelog? ✅ 
-   PR title properly formatted (`[XX-000]: description`)? ✅
-   Contains e2e tests ❌
-   Is accessible ✅ ❌
-   Compatible with Studio ✅
-   Cross-browser compatible ✅
-   Comply with designs ✅
-   Comply with PM's requirements ✅
-   [ ] Bug fix
-   [ ] Feature
-   [X] Refactor
Fix the issue when logo rendered instead of language selector arrow
Changed the `img` tag to `div` with `background-image` because logo is applied to all `img` tags in the navbar.
=> [WC-1351]: fixed the problem with rendering logo

packages/modules/web-actions/CHANGELOG.md, packages/modules/web-actions/package.json
Update `web-actions` changelog, bump version and update supported studio pro version.
-   [ ] New …
=> [WC-1325] Prepare 2.6.0 release

packages/modules/data-widgets/package.json, packages/modules/web-actions/package.json
Enable publish script for modules
-   [ ] New feature (non-breaking change which adds …
=> Add missing publish scripts for modules

.github/dependabot.yml
Prevent dependabot from checking major updates
=> ci(dependabot): ignore major updates

.github/dependabot.yml
Prevent dependabot from checking `typescript` updates (as we pinned this package, it meant to be updated manually)
=> ci(dependabot): ignore typescript updates

automation/e2e/package.json, automation/scripts/generate-dependabot-config.mjs, automation/scripts/package.json, pnpm-lock.yaml, pnpm-workspace.yaml
This is just small script that generates and writes `dependabot.yml` config. Just in case we need do some config changes.
=> ci(dependabot): add script to update dependabot config

packages/pluggableWidgets/html-element-web/package.json, packages/pluggableWidgets/html-element-web/src/components/HTMLTag.tsx, packages/pluggableWidgets/html-element-web/src/components/__tests__/HTMLTag.spec.tsx, packages/pluggableWidgets/html-element-web/src/components/__tests__/__snapshots__/HTMLTag.spec.tsx.snap, packages/pluggableWidgets/html-element-web/src/utils/__tests__/props-utils.spec.ts, packages/pluggableWidgets/html-element-web/src/utils/props-utils.ts, pnpm-lock.yaml
We changed HTMLTag component and added dompurify library to sanitize raw html that is coming as property.
-   [X] All new and existing tests passed
-   [X] I run `lint` command locally and it doesn’t give errors
-   [ ] Bug fix (non-breaking change which fixes an …
=> [WC-1328]: sanitize html in HTML element

packages/tools/release-utils-internal/src/steps.ts
We removed git cleanup as this prevents us to push new files.
-   [X] Bug fix (non-breaking change which fixes an issue)
=> fix(release-utils-internal): remove the git cleanup

packages/pluggableWidgets/html-element-web/CHANGELOG.md, packages/pluggableWidgets/html-element-web/package.json
The HTML widget was published, so we add appNumber from marketplace as well as enabling release automation for the widget.
-   [X] No code changes (changes to documentation, CI, metadata, etc)
=> chore(html-element-web): enable release script for the widget

packages/modules/data-widgets/package.json
Module version bump for the release of 2.5.8
=> chore(data-widgets): bump version to 2.5.8

.github/dependabot.yml, automation/scripts/generate-dependabot-config.mjs
This change update config generator. Now generated config includes ignore rules for local (workspace) packages.
=> [WC-1535]: Configure dependabot to ignore local packages

.github/workflows/Build.yml
=> ci: us head_ref to get PR branch

.github/workflows/Renovate.yml
Update cron expression for renovate workflow.
=> ci: update renovate schedule

packages/pluggableWidgets/barcode-scanner-web/CHANGELOG.md, packages/pluggableWidgets/barcode-scanner-web/package.json, packages/pluggableWidgets/barcode-scanner-web/src/package.xml, pnpm-lock.yaml
Update zxing library to v0.19.1
=> [WC-1590]: build(barcode-scanner-web): update zxing library

automation/run-e2e/lib/setup-test-project.mjs
Add console.error statement for better error visibility.
-   [x] Bug fix (non-breaking change which fixes an issue)
=> fix(run-e2e): log error on unzip failure

packages/pluggableWidgets/charts-web/CHANGELOG.md, packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml, packages/shared/charts/package.json, pnpm-lock.yaml
-   [X] PR title properly formatted `[XX-000]: description`
-   [X] Added record to packages' CHANGELOG.md
-   [X] Bumped package version in `package.json` and `package.xml`
-   [X] No code changes (changes to documentation, CI, metadata, etc)
-   [X] Dependency changes (any modification to dependencies in `package.json`)
=> [WC-1617]: update fast-json-patch dependency

package.json
=> fix: update "version" and "changelog" command at root package

package.json, pnpm-lock.yaml
An update created by running `pnpm audit --fix`
-   [x] Dependency changes (any modification to dependencies in `package.json`)
=> chore(deps): add package overrides to fix security issues

packages/pluggableWidgets/maps-web/package.json, pnpm-lock.yaml
Update dependencies:
- remove faker ([not used](https://github.com/mendix/web-widgets/search?q=faker))
- update leaflet -> 1.9.3
- remove @types/googlemaps (deprecated)
- update @googlemaps/jest-mocks -> 2.7.5
-   [x] Dependency changes (any modification to dependencies in `package.json`)
=> chore(deps): update maps-web

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/package.xml
=> chore(rich-text-web): prepare rich-text-web release

automation/utils/src/package-info.ts, packages/pluggableWidgets/google-tag-web/.eslintrc.json, packages/pluggableWidgets/google-tag-web/.prettierrc.js, packages/pluggableWidgets/google-tag-web/CHANGELOG.md, packages/pluggableWidgets/google-tag-web/README.md, packages/pluggableWidgets/google-tag-web/package.json, packages/pluggableWidgets/google-tag-web/src/GoogleTag.editorConfig.ts, packages/pluggableWidgets/google-tag-web/src/GoogleTag.tsx, packages/pluggableWidgets/google-tag-web/src/GoogleTag.xml, packages/pluggableWidgets/google-tag-web/src/commonGtag.ts, packages/pluggableWidgets/google-tag-web/src/package.xml, packages/pluggableWidgets/google-tag-web/src/utils.ts, packages/pluggableWidgets/google-tag-web/tsconfig.json, packages/pluggableWidgets/google-tag-web/typings/GoogleTagProps.d.ts, packages/pluggableWidgets/google-tag-web/typings/global.d.ts, pnpm-lock.yaml
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or …
=> [WC-1608]: add google tag web widget

packages/pluggableWidgets/google-tag-web/package.json
Add missing `mpkName` field to `google-tag-web`
=> chore(google-tag-web): add mpkName filed

packages/pluggableWidgets/color-picker-web/cypress/integration/ColorPicker.spec.js
---
Add retries to the color picker e2e test when running on Firefox. I'm following the same approach we're using on Chrome.
=> Add retries to the Firefox e2e test of color picker widget

packages/modules/data-widgets/package.json
---
Fix mx version - add build number
---
=> fix(data-widgets): add missing build to mx version

packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/dropdown-sort-web/package.json, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/tree-node-web/package.json
Pin all test projects to corresponding package version.
=> chore(data-widgets): update testProject branches

.github/configs/labeler.yml, .github/pull_request_template.md
---
Update labeler configuration and remove line separator from pr template
=> chore(web-widgets): update github files

packages/modules/data-widgets/package.json, packages/modules/web-actions/package.json, pnpm-lock.yaml
Remove unused package
-   [x] Dependency changes (any modification to dependencies in `package.json`)
=> chore(data-widgets,web-actions): remove unused cross-env package

automation/run-e2e/lib/docker-utils.mjs, automation/run-e2e/package.json, pnpm-lock.yaml
---
Update cypress to version 12.6 and also the docker image.
=> Update cypress to version 12.6

packages/pluggableWidgets/tooltip-web/package.json, pnpm-lock.yaml
---
Remove deprecated types package for `popper.js`
=> build(tooltip-web): remove deprecated package

package.json, pnpm-lock.yaml
---
This is important patch as in 1.8.1 they introduced bug that lead our CI to fail, like in #396
=> fix(deps): update turbo to 1.8.2

package.json, pnpm-lock.yaml
---
One more `turbo` patch to fix CI failures introduced after updating to `turobo@1.8.0`
=> fix(deps): update turbo to fix ci fails

automation/run-e2e/lib/docker-utils.mjs, automation/run-e2e/package.json, pnpm-lock.yaml
=> Update cypress to 12.7

.github/renovate.json
---
This RP changes renovate configuration to change PR priority.
- Now all dev dependencies has lower priory over prod.
- `mendix` dependency marked as high priority.
=> ci(renovate): configure renovate pr priority

.github/renovate.json
=> ci(renovate): fix renovate config

.husky/commit-msg, automation/scripts/package.json
---
`commitlint` was failing on windows because `$1` was never expanded to commit message path. Now it fixed.
=> fix(web-widgets): windows issue with commit lint

packages/modules/data-widgets/package.json
---
Module version bump for the release of 2.6.1.
=> chore(data-widgets): bump version to 2.6.1

packages/pluggableWidgets/html-element-web/src/HTMLElement.editorPreview.tsx, packages/pluggableWidgets/video-player-web/src/components/Html5.tsx
---
Small fixes to resolve eslint errors
=> fix: resolve eslint erros after react plugin update

packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.editorConfig.ts, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.xml, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/Gallery.spec.tsx, packages/pluggableWidgets/gallery-web/src/package.xml, packages/pluggableWidgets/gallery-web/typings/GalleryProps.d.ts, packages/shared/pluggable-widgets-commons/src/index.ts, packages/shared/pluggable-widgets-commons/src/selection/index.ts
---
Add item selection implementation to Gallery based on new "selection" property from Pluggable Widgets API.
E2E updates:
Test for sorting actually was testing enum filtering. To fix that I added new test case and moved enum filtering to appropriate test group.
=> [WC-1636] Gallery selection API

packages/modules/google-tag/CHANGELOG.md, packages/modules/google-tag/package.json, packages/modules/web-actions/CHANGELOG.md, packages/modules/web-actions/package.json
Version bumps, no code changes.
---
Bump version to 9.18.4 and above.
=> [WC-1718]: bump min supported version

.github/workflows/Renovate.yml
---
Update renovate GH action to 36
=> chore(deps): update renovate gh action to v36

packages/modules/data-widgets/package.json, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery-design-properties.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/design-properties.json, packages/pluggableWidgets/gallery-web/src/Gallery.editorConfig.ts, packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.tsx, pnpm-lock.yaml
---
Add default styles for gallery selection.
=> [WC-1738]: gallery selection styles

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, packages/pluggableWidgets/gallery-web/src/Gallery.editorConfig.ts, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx, packages/pluggableWidgets/selection-helper-web/CHANGELOG.md, packages/pluggableWidgets/selection-helper-web/README.md, packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.tsx, packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.xml
Small changes in texts and props. 
---
=> [WC-1769]: fix feedback

packages/customWidgets/calendar-web/package.json
---
Adding @mendix to the name of calendar-web to prevent snyk warnings.
=> [WC-1702]: update calendar-web name to prevent snyk conflict

.github/workflows/BuildJobs.yml, automation/run-e2e/cypress.config.cjs, automation/run-e2e/package.json, pnpm-lock.yaml
---
This MR  is part of the crafting days, which adds the possibility to generate a test report with all the steps performed in the e2e as an HTML file. That simplifies the way to debug when we have a failed step in the e2e. There are two ways to use these scripts:
- Downloading from the build artifacts since now that is part of our e2e automation workflow;
- Or use when running RC test locally, then it's possible to generate this report to add in the RC test evidence.
As part of that it was added a new configuration in the Cypress, and added the `mochawesome` packages to generate and merge the report json files through the specs.
=> [WC-1740] Add e2e test report generation

.github/workflows/BuildJobs.yml, automation/run-e2e/package.json
---
Count the files on the test report workflow then only execute it when necessary.
=> Count the files when generating test report

package.json, pnpm-lock.yaml
---
With PWT v9.24.0 we struggling with packages that require React 18 as peer dependency. For now we pin PWT to 9.23 and postpone migration.
=> chore(deps): pin PWT to 9.23 for all packages

automation/utils/src/steps.ts, packages/modules/anychart-buildingblocks/package.json
---
Add missing steps for anychart module publishing and fix issue with permissions as shelljs fail when `cp`.
Looks like some dirs not writable after module export or git clone.
=> Fix anychart module publish automation

.github/workflows/BuildJobs.yml
---
Add failure condition in the test report execution, since the test report is more useful when we have a failure and we don't need this step executed all the time.
=> Add failure condition in the test report execution

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Table.spec.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/package.xml, packages/pluggableWidgets/selection-helper-web/CHANGELOG.md, packages/pluggableWidgets/selection-helper-web/package.json, packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.tsx, packages/pluggableWidgets/selection-helper-web/src/package.xml, packages/shared/pluggable-widgets-commons/src/selection/context.ts
---
Selection helper works in the header section of DG2, additionally it should still work in Gallery as this PR does some small changes in Gallery as well.
=> [WC-1767] Support Selection helper in DG2

automation/utils/src/package-info.ts, packages/pluggableWidgets/dropdown-web/package.json
---
* Renaming dropdown package to have `@mendix/` prefix
* Making sure all packages have the `@mendix/` prefix by adding a schema validation
=> [WC-1624] Rename remaining pkgs

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml
Bump version of affected widget in virtual scrolling issue
=> [WC-1349] virtual scroll issue - bump widgets version

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/tree-node-web/CHANGELOG.md
---
Updating chagelogs of data-widgets and it's dependencies to prevent failing during release checks
=> fix(changelogs): add whitespaces in changelog bullets

packages/shared/pluggable-widgets-commons/src/components/web/preview.ts
Since preview mode passes different (correct) icon format we have to align with new typings while still keeping backwards compatibility with existing old typings.
=> [WC-1789] On the way to PWT 9.24

packages/modules/web-actions/CHANGELOG.md, packages/pluggableWidgets/area-chart-web/CHANGELOG.md, packages/pluggableWidgets/bar-chart-web/CHANGELOG.md, packages/pluggableWidgets/bubble-chart-web/CHANGELOG.md, packages/pluggableWidgets/column-chart-web/CHANGELOG.md, packages/pluggableWidgets/heatmap-chart-web/CHANGELOG.md, packages/pluggableWidgets/line-chart-web/CHANGELOG.md, packages/pluggableWidgets/pie-doughnut-chart-web/CHANGELOG.md, packages/pluggableWidgets/time-series-chart-web/CHANGELOG.md
=> style: fix changelog formatting for charts

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-filters.scss, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml
---
The z-index was set low for the `dropdown-content`, therefore multiple layers of modal/popups cause visibility issues after a while, now it is a higher value and shouldn't cause similar issues.
Need to make sure multiple layers of modal/popups doesn't break the dropdown. JIRA Story has a nice test project where issue can be reproduced.
=> [WC-1343]: Change z-index to solve dropdown visibility

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss
---
Client found some "dead" code in our styling. So, after checking, and confirming that yes, this styles has no impact on UI we remove them to make styling easier.
You can build theme and run datagrid, and then just play with "align" property, the behavior should not change.
=> [WC-1724]: Remove dead styling

packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml
---
Prepare DataGrid filters for release
=> [WC-1820] chore: prepare widgets for release

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Table.spec.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
---
We fix issue with textarea and other input elements that placed inside row with "onClick" action. Configured onClick action   was triggering on any space or enter event. Now it triggered only when cell is in focus. This allow typing "Enter" and "Space" in text area.
Create empty datagrid with column that has custom content. Add textbox or textarea widget to the column. Now run the app and try to add paragraph of text. You should see no issues while typing text.
=> [WC-1269] Keyboard event handling for row actions

automation/run-e2e/cypress.config.cjs, automation/run-e2e/package.json, automation/run-e2e/support/commands.mjs, packages/pluggableWidgets/carousel-web/cypress/integration/Carousel.spec.js, packages/pluggableWidgets/datagrid-web/cypress/integration/DataGrid.spec.js, pnpm-lock.yaml
---
Enables the usage of the cypress-axe plugin to check a11y violations during the e2e testing phase. That's the first widget since we fixed the a11y issues recently, the idea is to spread the usage through all widgets with e2e automation enabled.
=> [WC-1953] Enable a11y testing with cypress-axe plugin

packages/pluggableWidgets/tooltip-web/CHANGELOG.md, packages/pluggableWidgets/tooltip-web/package.json, packages/pluggableWidgets/tooltip-web/src/package.xml, packages/pluggableWidgets/tooltip-web/src/ui/Tooltip.scss
---
When a tooltip was positioned to top inside a datagrid table it was not showing completely, because the table header was positioned in front of it.
To fix the issue with the tooltip it is necessary to update data widgets with the last version from marketplace.
=> [WC-1585]: tooltip not showing when its close to table head

packages/pluggableWidgets/progress-circle-web/package.json, packages/pluggableWidgets/progress-circle-web/src/components/Circle/Circle.ts, packages/pluggableWidgets/progress-circle-web/src/components/Circle/Path.ts, packages/pluggableWidgets/progress-circle-web/src/components/Circle/Shape.ts, packages/pluggableWidgets/progress-circle-web/src/components/Circle/Types.ts, packages/pluggableWidgets/progress-circle-web/src/components/Circle/Utils.ts, packages/pluggableWidgets/progress-circle-web/src/components/ProgressCircle.tsx, packages/pluggableWidgets/progress-circle-web/src/components/__tests__/ProgressCircle.spec.tsx, pnpm-lock.yaml
adopt https://github.com/kimmobrunfeldt/progressbar.js/tree/master/src directly to our code to solve security issue on attribute extends.
snyk issue: https://app.snyk.io/org/appstore/project/19cf3a0a-f669-4b4b-a7f9-85500b52a22d
please treat this the same way as changing library: need to retest everything on progress circle
=> [WC-1903] Fix progress circle security issue

packages/modules/data-widgets/package.json, packages/pluggableWidgets/progress-circle-web/package.json, packages/pluggableWidgets/progress-circle-web/src/package.xml
to support treenode release and progress circle
=> chore: version bump

packages/pluggableWidgets/progress-circle-web/CHANGELOG.md
add changelog for progress-circle
=> chore: add changelog

packages/pluggableWidgets/tooltip-web/CHANGELOG.md, packages/pluggableWidgets/tooltip-web/src/components/Tooltip.tsx
---
When using a disabled input inside tooltip widget with hover event, the tooltip would open but not close.
=> [WC-1851]: Fix tooltip hover issue

packages/pluggableWidgets/line-chart-web/CHANGELOG.md, packages/pluggableWidgets/line-chart-web/package.json, packages/pluggableWidgets/line-chart-web/src/LineChart.editorConfig.ts, packages/pluggableWidgets/line-chart-web/src/LineChart.tsx, packages/pluggableWidgets/line-chart-web/src/LineChart.xml, packages/pluggableWidgets/line-chart-web/src/__tests__/LineChart.spec.tsx, packages/pluggableWidgets/line-chart-web/typings/LineChartProps.d.ts, packages/shared/charts/src/hooks/usePlotChartDataSeries.ts
---
Fix line chart by linking text templates for line color and marker color settings to datasouce.
Now, when configuring line color or marker color you can use entity attributes to build expression.
Line color and marker color expressions should be tested. Expected result is that you can use entity attribute to crate dynamic text.
=> [WC-1992] Line chart fix line color

packages/pluggableWidgets/tree-node-web/CHANGELOG.md, packages/pluggableWidgets/tree-node-web/package.json, packages/pluggableWidgets/tree-node-web/src/components/hooks/useKeyboardHandler.tsx, packages/pluggableWidgets/tree-node-web/src/package.xml
---
This PR fixes the issue with keyboard event propagation through the tree node container. Now the tree node container handles only its own events and lets child events pass through, so "enter" and " " (space) keyboard events can pass through and be handled correctly and, as a result, can be seen in input elements.
You need to create a tree node with a custom header and custom content. Put a text box and a text area as a child.
Expected: After running the project, you should be able to type `" "` (space) and use "enter" and arrow keys in the input and textarea.
=> [WC-1887] Fix: container handles only own events

packages/pluggableWidgets/line-chart-web/src/LineChart.xml
---
Convert color properties in a line chart from a text template to an expression.
Same steps as in #650
=> feat(line-chart-web): convert color props to expression

automation/run-e2e/lib/docker-utils.mjs, automation/run-e2e/package.json
---
Improve logging for our e2e test by piping logs from runtime to main process.
=> feat(run-e2e): pipe runtime logs to parent process

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
---
As of now, in the header part, table passed incorrect index to function that should render header wrapper. Now index is passed correctly.
You show see no errors in design mode preview for Data grid.
=> fix(datagird-web): fix preview issue by passing correct index and useless warning (WC-1912)

packages/pluggableWidgets/combobox-web/src/Combobox.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/MultiSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/SingleSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/assets/icons.tsx, packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
- fix styling on combobox
- added checkbox icon 
- move icon style to css
- fix error shown when no data exist
- fix multiselect (boxes) not filtered when option is already selected
=> feat(combo-box): [WC-1978] combobox styling

packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/features/export.ts, packages/pluggableWidgets/datagrid-web/typings/global.d.ts
---
Creating an export API to handle any kind of export on Datagrid2, be it JSON, SQL, CSV, XLS, ...
=> [WC-1598]: DataGrid2 Export API

packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/components/ComboboxMenuWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/BaseAssociationSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/EnumBool/EnumBoolSingleSelector.tsx, packages/pluggableWidgets/combobox-web/src/hooks/useActionEvents.ts, packages/pluggableWidgets/combobox-web/tsconfig.json, pnpm-lock.yaml
---
Migrate last package to the new plugins system.
=> refactor(combobox-web): remove pwc

automation/run-e2e/lib/docker-utils.mjs
---
Remove unnecessary docker manifest inspect command execution which sometimes causes the e2e automation to fail.
=> Remove unnecessary docker manifest inspect

.github/workflows/CreateGitHubRelease.yml
---
Add workflow field to have better "run" names.
=> chore: update run-name for release workflow

.github/workflows/BuildJobs.yml, .github/workflows/CreateGitHubRelease.yml, .github/workflows/PublishMarketplace.yml, .github/workflows/RunE2EFirefox.yml, package.json, pnpm-lock.yaml
---
- Update pnpm to 8.8.0
- Update turob to 1.10.14
- Remove the pnpm version from workflows (the pnpm/setup-action will use "pacakgeManager" from package.json)
- Update pacakge.json
=> [WC-2162] Update pnpm, turbo and engines

packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/EnumBool/EnumBoolOptionsProvider.ts, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
Refactoring ,
change filter type no -> none
show no options text when filter type is none.
move no options text to be under filter type
=> [WC-2055] feat(combobox): hide no option text on filter none

packages/pluggableWidgets/image-web/package.json, packages/pluggableWidgets/image-web/src/package.xml
update changelog and version for image-web to prepare for release
=> [WC-2126]chore(image-web): update changelog and version

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml
=> feat(data-widget): update version and changelog

packages/pluggableWidgets/combobox-web/src/Combobox.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/MultiSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/SingleSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
---
Added focus state styles, aria-label, and behavior change in Clear button, when it is cleared, the focus will go to input field as requested.
The changes in description should behave properly without causing a11y glitches on keyboard, aria-label should be visible with "Clear selection" value, and clear button now should have a focus state style. 
-->
=> [WC-2144][WC-2150]: Combobox a11y adjustments, keyboard navigation for Multi

packages/pluggableWidgets/charts-web/CHANGELOG.md, packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml, packages/shared/charts/src/components/Chart.tsx, packages/shared/charts/src/hooks/usePlotChartDataSeries.ts
---
Fix "On click" error for datasources with aggregation
=> [WC-2189]: Chart aggregation fix

.github/workflows/RunSigridCI.yml
---
Add workflow for [sigrid](https://github.com/Software-Improvement-Group/sigridci) integration.
=> [WC-1943] Add Sigrid CI workflow

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts
---
Fix issue with editorPreview re-render
=> [WC-2207] Fix issue with editorPreview re-render

packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts
---
Aligned behaviour of selecting items with Space and Enter in multi-selection.
Default with Enter was that input is cleared when item is toggled, these changes make sure Space button behaves same way.
Seeing if input is cleared when selecting/unselecting items with Space.
=> [WC-2145]: Set input value empty when toggling items (Multi-select)

packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/MultiSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/assets/icons.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationSimpleCaptionsProvider.tsx, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
Refactoring : update checkbox to use input tag
=> fix: change checkbox to use input tag

packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationMultiSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/helpers/utils.ts, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
new feature:
make combobox multi selection method to be configurable:
checkbox and rowclick
if checkbox,
- display checkbox for selected items, same with current behavior
if rowclick
- hide checkbox, filter options from selected items
=> [WC-2146] feat(combobox): allow multiselection method type to be configureable

.github/workflows/RunSigridCI.yml
=> chore: disable sigrid until issue with token is resolved

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/features/settings.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
---
Fix error that prevents configuration from being read correctly.
=> [WC-2205] Fix column numbering issue in personalisation

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
---
Fix regression. Now columns should stay in sync with props.
=> [WC-2223] fix(datagrid-web): update columns on change

automation/run-e2e/cypress.config.cjs, automation/run-e2e/package.json, automation/run-e2e/utils/read-excel.cjs, packages/pluggableWidgets/datagrid-web/cypress/integration/DataGrid.spec.js, pnpm-lock.yaml
---
Added a new E2E test case to check if the output generated by the Excel Export action is valid.
=> [WC-2195] Add export to Excel test case

packages/pluggableWidgets/combobox-web/src/assets/icons.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationSimpleCaptionsProvider.tsx
---
dropdown automatically closing due to lost focus.
child input and label received focus on click, 
this changes disabled it.
=> fix: disable input in checkbox and label focus

packages/pluggableWidgets/rich-text-web/src/ui/RichText.scss
---
inconsistent padding in hover causes weird behavior for the toolbar icons,
this changes forced that padding to be exactly the same on and off hover.
=> [WC-2192] fix: toolbar issue on hover inconsistent padding

packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/src/components/__tests__/Gallery.spec.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/__mocks__/intersectionObserverMock.ts, packages/shared/widget-plugin-grid/package.json, packages/shared/widget-plugin-grid/src/components/InfiniteBody.tsx, packages/shared/widget-plugin-hooks/src/useOnScreen.ts, pnpm-lock.yaml
---
Add a hook to observe when component is visible on screen. Use the hook to determine when useInfiniteScroll should update and recalculate the height.
This hook fixes a weird behavior on Gallery widget where there is no vertical scroll on an infinite scroll gallery
=> [WC-2200]: Fix virtual scrolling for Gallery Widget

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/components/Row.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx
---
Now whole column should be clickable, not only header.
=> [WC-2206] Fix column issue for dg2 in design mode

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/package.xml
=> fix: update RTE version for release

packages/pluggableWidgets/charts-web/CHANGELOG.md, packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml, packages/shared/charts/package.json, packages/shared/charts/src/components/Chart.tsx
---
I found that the issue is due to array merging is incorrect if "undefined" data exist.
marker.colors data coming from database: [undefined, undefined, undefined]
if added marker.colors configuration, then previously it becomes this: [undefined, undefined, undefined, customdata1, customdata2 ]
I fixed this by removing all undefined value from arrays before merging it.
=> fix: chart color not customizeable

packages/pluggableWidgets/datagrid-web/src/components/Cell.tsx, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Header.spec.tsx, packages/pluggableWidgets/datagrid-web/src/features/settings.ts, packages/pluggableWidgets/datagrid-web/src/features/use-columns-state.ts, packages/pluggableWidgets/datagrid-web/src/helpers/Column.tsx, packages/pluggableWidgets/datagrid-web/src/helpers/ColumnBase.ts, packages/pluggableWidgets/datagrid-web/src/helpers/ColumnPreview.tsx, packages/pluggableWidgets/datagrid-web/src/typings/GridColumn.ts
Refactoring
---
Small improvements and cleanup.
=> [WC-2268] Dg2 personalization refactoring

packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md
=> fix(datagrid-dropdown-filter-web): fix changelog format

packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Header.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Table.spec.tsx, packages/pluggableWidgets/datagrid-web/src/features/__tests__/settings.spec.ts, packages/pluggableWidgets/datagrid-web/src/helpers/Column.tsx, packages/pluggableWidgets/datagrid-web/src/helpers/ColumnPreview.tsx, packages/pluggableWidgets/datagrid-web/src/typings/GridColumn.ts, packages/pluggableWidgets/datagrid-web/src/utils/test-utils.tsx
=> refactor(datagrid-web): change column id type

packages/pluggableWidgets/combobox-web/src/Combobox.xml
---
Add translations for Dutch
=> [WC-2265] feat(combobox-web): add translations for Dutch

.github/workflows/RunE2EPlaywright.yml
Test-related change (New E2E test, test automation, etc.)
---
The new playwright workflow should run only where the script `e2e.playwright` is present.
Automation should run only where the script is available.
=> Fix playwright workflow missing script

.github/workflows/RunE2EPlaywright.yml
---
Add config path in the playwright execution
=> Add config path in the playwright execution

.github/workflows/RunE2EPlaywright.yml, automation/run-e2e/lib/playwright.mjs, automation/run-e2e/playwright.config.cjs, packages/pluggableWidgets/badge-web/package.json
---
As part of crafting, in this PR I'm refactoring playwright workflow execution to use the execution of the test project through the webServer config from Playwright. Additionally, I'm disabling chunks(matrix) execution for now, because there's only one spec available.
=> [CRAFTING] Refactoring playwright workflow execution

.github/workflows/RunE2EPlaywright.yml
---
Add GH token to the Playwright workflow.
=> Add GH token to the Playwright workflow

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/components/ComboboxMenuWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationSimpleCaptionsProvider.tsx, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/hooks/useActionEvents.ts, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftSingleSelectProps.ts, packages/pluggableWidgets/combobox-web/src/hooks/useMenuPlacement.ts, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
---
Add a "Show footer" boolean property to combobox, when set to true, enables the developers to place widgets (like text, buttons, links) on the combobox menu footer)
Footer example:
Structure mode:
Design mode:
=> [WC-2199]: Add show footer property to combobox-web

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/EnumBool/EnumBoolOptionsProvider.ts
…objects
---
The matchSorter package we are querying the user inputs has a sorter which defaults to alphabetical order.
We override it with no sorting at all to respect the sort order set in Studio Pro.
Both Associations and Enumeration values should show items in combobox menu in the order set in Selectable objects field.
=> [WC-2277]: Combobox override matchSorter default sorter for selectable objects

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/components/ComboboxMenuWrapper.tsx, packages/pluggableWidgets/combobox-web/src/hooks/useMenuStyle.ts
---
Added one more control to see if the menu flip causes another collision on top of the screen, which should now be pushed back to the screen.
The story has example of the case, instead of what's seen in the screenshot, the new behavior is pushing the menu as much necessary to make the top of it visible again, this has a side effect of covering/hiding the input field with the menu.
=> [WC-2298]: Combobox add top of screen collision handling 

packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx
---
There is no sense in showing clear button on the selected item labels in multi selection when combobox is read-only.
Multi selection, selected items should be shown as labels, the "x" shouldn't render when the combobox is set to `Editability: Never`
=> [WC-2279]: Combobox remove clear button from labels when readOnly 

.github/workflows/RunE2ERCNightlies.yml
---
This is the first step to enable the E2E automation to run against an RC build.
=> [WC-1659] Add new workflow for RC testing

packages/pluggableWidgets/popup-menu-web/CHANGELOG.md, packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/__tests__/__snapshots__/Menu.spec.ts.snap, packages/pluggableWidgets/popup-menu-web/src/__tests__/__snapshots__/PopupMenu.spec.ts.snap, packages/pluggableWidgets/popup-menu-web/src/components/Menu.tsx, packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx, packages/pluggableWidgets/popup-menu-web/src/package.xml
---
After switching to React Portal, the element we apply the class has changed. We are reverting the change, and applying it on the PopupMenu widget itself, rather than the child portal that pops up.
See which element the class is applied. Iy should be on the wrapping widget, not the menu that pops up.
=> [WC-2247]: PopupMenu: change the element class is applied

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/hooks/useActionEvents.ts, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftSingleSelectProps.ts
---
We had a blur() method being used inside onSelectedItemChange of the downshift configuration. Reverting it solves the issue.
Currently the blur() is called on combobox when an item is selected. 
With this PR the focus on combobox shouldn't be lost when an item is selected (single selection).
=> [WC-2281]: Combobox losing focus on item selection (single selection)

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts
---
A falcon (Fabian) were flying over our tree and spotted a bug. 🐛 😄
=> fix: change how we calc version range

packages/pluggableWidgets/combobox-web/package.json
=> chore(combobox): set app Number

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationMultiSelector.ts, packages/pluggableWidgets/combobox-web/src/package.xml
=> [WC-2327] fix: selected items not showing on custom content

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/features/export.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
---
Added a check to see if dynamic texts are returning `"undefined"` with `status:"loading"`, so that we can wait and update the value in next datasource update.
Try exporting a dg2 with dynamicText column items, at its current state it will export empty (`""`) string. 
With this change it should be exporting it too.
=> [WC-2300]: DG2: fix not exporting dynamicText

automation/run-e2e/docker/mxbuild.Dockerfile, automation/run-e2e/lib/docker-utils.mjs
---
Change to Mendix net6 image and force linux platform docker image, that will enable ARM machines to run the e2e test locally.
=> Use mendix net6 image and force linux platform docker image

packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/components/ColumnResizer.tsx, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx, packages/pluggableWidgets/datagrid-web/src/features/model/resizing.ts, packages/pluggableWidgets/datagrid-web/src/features/model/use-grid-state.ts, packages/pluggableWidgets/datagrid-web/src/typings/GridModel.ts, packages/pluggableWidgets/datagrid-web/src/utils/test-utils.tsx
---
In this PR I'm trying to fix colum resizing. Right now we resize only single column and let rest to be calculated by CSS. This approach give "stretch" feeling on resize (by resizing on column, all other columns resize as well). As a solution I'm trying to set fixed width for each column on resize start.
- Column resizing
Before:
---
After:
=> [WC-2288] DataGrid: fix column resizing 

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/Combobox.xml
=> [WC-2287]fix: minor label fix

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/src/utils/ckeditorConfigs.ts, pnpm-lock.yaml
---
Since yesterday we started to receive one alert from the CKEditor 4, we're disabling the version check in the CKEditor config to avoid this unnecessary alert.
=> [WC-2347][WC-2348] Disable version check in the CKEditor config, add validation message

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx
Bug Fix
---
no option text not showing on single selection
=> [WC-2350]fix: no option text not showing on combo box

.github/workflows/RunE2EModernClient.yml, automation/run-e2e/lib/docker-utils.mjs
---
Created a new workflow to run our E2E using a modern client feature flag running nightly.
=> [WC-2351] E2E using modern client

packages/pluggableWidgets/app-events-web/src/AppEvents.editorConfig.ts, packages/pluggableWidgets/app-events-web/src/AppEvents.tsx, packages/pluggableWidgets/app-events-web/src/AppEvents.xml, packages/pluggableWidgets/app-events-web/src/__tests__/AppEvents.spec.tsx, packages/pluggableWidgets/app-events-web/src/hooks/timer.ts, packages/pluggableWidgets/app-events-web/typings/AppEventsProps.d.ts
---
adding interval feature to component load.
interval timer will execute after initial delay.
=> [WC-2323]feat(app-events): add interval timer

packages/pluggableWidgets/rich-text-web/CHANGELOG.md
=> fix: changelog

.github/workflows/BuildJobs.yml, .github/workflows/RunE2ERCNightlies.yml, automation/run-e2e/docker/mxbuildRC.Dockerfile, automation/run-e2e/docker/mxruntimeRC.Dockerfile, automation/run-e2e/lib/docker-utils.mjs
---
Update RC E2E nightly workflow to use AWS S3 SP artifacts (mxbuild and runtime).
Extra: updated all GH action versions in the build workflow.
E2E automation should pass without any error.
=> [WC-1659] Update RC E2E nightlies to use AWS S3 SP artifacts

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/ListItem.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/Gallery.spec.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/__snapshots__/Gallery.spec.tsx.snap, packages/pluggableWidgets/gallery-web/src/features/item-interaction/ItemEventsController.ts, packages/pluggableWidgets/gallery-web/src/features/item-interaction/__tests__/item-keyboard.spec.tsx, packages/pluggableWidgets/gallery-web/src/features/item-interaction/action-handlers.ts, packages/pluggableWidgets/gallery-web/src/features/item-interaction/item-handlers.ts, packages/pluggableWidgets/gallery-web/src/features/useGridPositions.ts, packages/pluggableWidgets/gallery-web/src/helpers/SelectActionHelper.ts, packages/pluggableWidgets/gallery-web/src/package.xml, packages/shared/widget-plugin-grid/src/selection/__tests__/helpers.spec.ts, packages/shared/widget-plugin-grid/src/selection/helpers.ts, packages/shared/widget-plugin-grid/src/selection/keyboard.ts, packages/shared/widget-plugin-grid/src/selection/select-action-handler.ts, packages/shared/widget-plugin-grid/src/selection/types.ts
---
Adding a new feature to Gallery: You can use the keyboard to select multiple items inside the gallery, just as simple as shift + arrow keys. You can also unselect an item with shift+space.
* Shift + arrow up
* Shift + arrow down
* Shift + arrow left
* Shift + arrow right
* Shift + Home
* Shift + End
* Shift + Page Up
* Shift + Page Down
=> [WC-2175]: Gallery Multi Selection

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/BaseOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/EnumBool/EnumBoolOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/utils.ts
---
The idea is to return the ranked sorting again to combobox, but only when user starts typing something.
=> [WC-2341]: Change Combo Box to allow for Ranked Sorting again

automation/run-e2e/lib/docker-utils.mjs, packages/pluggableWidgets/badge-button-web/cypress/integration/differentViews.spec.js, packages/pluggableWidgets/badge-web/cypress/integration/onClick.spec.js, packages/pluggableWidgets/image-web/cypress/integration/differentViews.spec.js, packages/pluggableWidgets/progress-bar-web/cypress/integration/differentViews.spec.js, packages/pluggableWidgets/slider-web/cypress/integration/Slider.spec.js
---
The second round of the e2e modern client fixes related to this PR: https://github.com/mendix/web-widgets/pull/943
=> [WC-2364] Fix test projects and specs to work with modern client: part 2

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/DatePicker.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/__snapshots__/DatagridDateFilter.spec.tsx.snap, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/__snapshots__/DatePicker.spec.tsx.snap, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/__snapshots__/FilterComponent.spec.tsx.snap, packages/pluggableWidgets/datagrid-date-filter-web/src/utils/utils.ts, pnpm-lock.yaml
---
To fix Jira ticket WC-2328, we are updating react-datepicker to latest version (6.4.0) which uses last version of date-fns and floating-ui instead of popper-js. Also, the datepicker uses `useAdditionalWeekYearTokens` set to `true` which fixes some issues that caused this Jira ticket.
=> [WC-2328]: Fix date format on datagrid-date-filter

automation/utils/bin/rui-update-changelog-module.ts, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml
=> chore(datagrid-web): bump version

packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml
=> chore(gallery-web): bump version for gallery-web widget

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/src/utils/contants.ts
---
adding baseUrl to let tinymce figure out correct path for skins and plugins.
=> [WC-2409] baseUrl fix for rich text editor

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/components/ComboboxMenuWrapper.tsx, packages/pluggableWidgets/combobox-web/src/package.xml
=> [WC-2320] scrollbar click issue causing combobox to close

.github/workflows/RunSigridCI.yml
---
Disable Sigrid feedback on GH pull requests.
=> chore: disable Sigrid comment in GH pull requests

.github/renovate.json, .github/workflows/Renovate.yml
---
1. Replace "global" options with their "env" counterparts
2. Migrate from old config to new config format
3. Remove redundant "if" statement that left after changes introduced in #288
4. Change cron schedule (reduce number of runs during the day).
=> chore: renovate maintenance

packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
---
Made the `visible` property for columns required since leaving it blank(`undefined`) causes a constant state of "loading", therefore keeping the DG in a constant "pending" state.
Test case from the story should be fixed, DG should be visible completely.
=> [WC-2421]: DG2: Make visible property required

packages/pluggableWidgets/datagrid-web/CHANGELOG.md
To be reflected as part of 2.16
=> chore: update changelogs for dg2

packages/pluggableWidgets/barcode-scanner-web/rollup.config.js, packages/shared/charts/src/rollup/index.js
---
This small change should fix failing build with PWT@v10.7.2.
After changes introduced in [#80 of widgets-tools](https://github.com/mendix/widgets-tools/pull/80) onwarn expects second parameter. Because of custom config, this parameter were missing and caused build to fail.
=> fix(barcode-scanner, charts): fix failing rollup build

.github/workflows/ClearActionsCaches.yml
---
Add cron job to clear all GitHub actions caches.
=> feat(workflows): add job to clear actions caches

.github/workflows/BuildJobs.yml, .github/workflows/CreateGitHubRelease.yml, .github/workflows/PublishMarketplace.yml, .github/workflows/Renovate.yml, .github/workflows/RunE2EFirefox.yml, .github/workflows/RunE2EModernClient.yml, .github/workflows/RunE2EPlaywright.yml, .github/workflows/RunE2ERCNightlies.yml, .github/workflows/RunSigridCI.yml
The build failed: https://github.com/mendix/web-widgets/actions/runs/8702497163 
Upgrading to latest versions to fix it.
=> fix gh actions after upgrade to node 20

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/helpers/ColumnPreview.tsx
---
Change default params for init column to prevent state where it marked as hidden by default.
=> [WC-2427] Fix issue with default column color

pnpm-lock.yaml
---
After updating pluggable widget tools to 10.7.2 jest bin file is not resolvable due to broken versions in lock file. This change should fix this issue.
=> chore: fix jest resolution after updating PWT to 10.7.2

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/components/Cell.tsx
---
As we switched to mobx we have to wrap cell into `observable` to update it whenever column store is updated.
=> [WC-2451] fix(datagrid-web): rerender on cell content change

packages/modules/data-widgets/package.json
=> chore(data-widget): update version

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
=> [WC-2402]: update a11y text as optional

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/helpers/Association/BaseAssociationSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseSingleSelector.ts
=> [WC-2311] do not retrieve full dropdown list when readonly

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/MultiSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/SingleSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/StaticSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx
---
Add role combobox to the Combobox Wrapper component
=> [WC-2392]: Combobox a11y role

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/helpers/utils.ts
---
The selected  items displayed inside the input on combobox are not following the same sort direction as the items inside the combobox menu.
=> [WC-2406]: Combobox sort displayed items on Multi Select

packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/package.xml
=> chore(combo-box): update version

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/rollup.config.js, packages/pluggableWidgets/rich-text-web/src/RichText.editorConfig.ts, packages/pluggableWidgets/rich-text-web/src/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/src/__tests__/RichText.spec.tsx, packages/pluggableWidgets/rich-text-web/src/__tests__/__snapshots__/RichText.spec.tsx.snap, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/ui/RichText.scss, packages/pluggableWidgets/rich-text-web/src/utils/helpers.ts, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
Bug fix with feature parity from previous version
- read only style
- input focus styling fix
- hide quick toolbar
- dimension setting fix
=> [WC-2407][WC-2404] RTE: readonly style, quick toolbar, and style

packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/package.xml
=> chore(rich-text): update version

packages/pluggableWidgets/events-web/CHANGELOG.md, packages/pluggableWidgets/events-web/package.json, packages/pluggableWidgets/events-web/src/hooks/timer.ts, packages/pluggableWidgets/events-web/src/package.xml
=> [WC-2429] Event not fired when using mf/nf param

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/helpers/state/column/BaseColumnInfo.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/column/ColumnStore.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/datagrid-web/src/utils/test-utils.tsx, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml, packages/shared/widget-plugin-grid/src/selection/keyboard.ts
---
Add prop to control event propagation on custom content.
=> [WC-2391] Add custom content events prop

packages/shared/widget-plugin-grid/src/components/Pagination.tsx
---
This is to fix the failing e2e tests condition in the pagination PR opened earlier on the same branch.
Pagination conditions should all work.
=> [WC-2417] dg2 pagination visibility fix

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/package.xml
=> [WC-2278]: Add auto-label feature to combobox-web widget

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx
=> [WC-2371]: show correct pagination count (Datagrid 2 and Gallery)

package.json, packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/src/ui/RichText.scss, pnpm-lock.yaml
=> [WC-2426][WC-2433]fix: tabIndex and SNYK-JS-TINYMCE-6501605 and SNYK-JS-TINYMCE-6501006

packages/pluggableWidgets/maps-web/CHANGELOG.md, packages/pluggableWidgets/maps-web/package.json, packages/pluggableWidgets/maps-web/src/package.xml, packages/pluggableWidgets/maps-web/src/utils/data.ts
---
Due to localization(Dutch/English in this tickets case) Lat/Lon values decimal points change ( `10.1` when English, `10,1` when Dutch).
`Number()` constructor doesn't handle the `,` case, therefore we need to sanitise it.
[The story has an attached project](https://mendix.atlassian.net/jira/software/c/projects/WC/boards/418/?selectedIssue=WC-2413) with the specific reproduction steps. Trying it with and without the fix branch will show how the issue manifests.
=> [WC-2413]: Maps - Handle comma decimal point case in Lat/Lon values

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/StaticSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/MultiSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/SingleSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/StaticSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Static/Preview/StaticPreviewSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/package.xml, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
Add readonly style to combobox
=> [WC-2430] add readonly style

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss
=> [WC-2282] use CSS variables in combobox 

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/README.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/src/__tests__/RichText.spec.tsx, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
---
add cut copy paste to rich text context menu (from tinymce menu)
and allow user to use native context menu as well.
=> fix: rich text context menu

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/cypress/integration/DataGrid.spec.js, packages/pluggableWidgets/datagrid-web/src/features/export.ts
---
When values are exported, numbers were being sent as string, this PR aims to fix that by sending the number instead of a string.
=> [WC-2441]: Fix datagrid export when exporting numbers

packages/modules/data-widgets/package.json, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-filters.scss, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml
=> [WC-2482] fix: undefined scss var for DG

packages/pluggableWidgets/datagrid-web/CHANGELOG.md
=> fix: datagrid changelog

.github/workflows/PullRequestFork.yml
---
Remoe command that fail GH action.
=> chore: remove gh command that fail welcome action

packages/pluggableWidgets/tree-node-web/CHANGELOG.md, packages/pluggableWidgets/tree-node-web/package.json, packages/pluggableWidgets/tree-node-web/src/components/HeaderIcon.tsx, packages/pluggableWidgets/tree-node-web/src/components/TreeNode.tsx, packages/pluggableWidgets/tree-node-web/src/components/TreeNodeBranch.tsx, packages/pluggableWidgets/tree-node-web/src/components/TreeNodeBranchContext.ts, packages/pluggableWidgets/tree-node-web/src/components/__tests__/TreeNode.spec.tsx, packages/pluggableWidgets/tree-node-web/src/components/hooks/useTreeNodeRef.ts, packages/pluggableWidgets/tree-node-web/src/package.xml
---
Fix the nested tree collapsing issue mentioned on [WC-2439] and also take some refactoring.
[WC-2439]: https://mendix.atlassian.net/browse/WC-2439?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WC-2439]: Fix nested tree node collapsing issue

packages/modules/data-widgets/package.json
=> chore: bump data-widgets minor version for tree-node-web release

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/src/utils/constants.ts, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
---
allow to include external styling in rich text.
also allowing to switch between built-in styling: default and dark via expression
=> [WC-2479] allow external styling in RTE

packages/pluggableWidgets/tooltip-web/CHANGELOG.md, packages/pluggableWidgets/tooltip-web/package.json, packages/pluggableWidgets/tooltip-web/src/package.xml, packages/pluggableWidgets/tooltip-web/src/ui/Tooltip.scss
---
content inside tooltip not supposed to forced to certain width.
this css is removed.
=> [WC-2497] removed forced fit-content width on tooltip

packages/modules/data-widgets/src/javascriptsource/datawidgets/actions/Reset_All_Filters.js, packages/modules/data-widgets/src/javascriptsource/datawidgets/actions/Reset_Filter.js, packages/pluggableWidgets/datagrid-date-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/features/select.ts, packages/shared/widget-plugin-external-events/src/hooks/useOnResetFiltersEvent.ts, packages/shared/widget-plugin-external-events/src/hooks/useOnResetValueEvent.ts, packages/shared/widget-plugin-external-events/src/hooks/useTransmit.ts, packages/shared/widget-plugin-filtering/src/controls/input/useValueFilterState.ts
New feature
---
adding options to setToDefault value for reset filter to allow user to reset to filter's default value instead of empty
related to https://github.com/mendix/DataWidgets-module/pull/11
=> [WC-2466] [WC-2463] update reset filter to add setToDefault

.github/workflows/RunE2EFirefox.yml, .github/workflows/RunE2EModernClient.yml, .github/workflows/RunE2ERCNightlies.yml
---
Fixes for the GH workflows using incorrect paths and executing old Cypress implementation.
=> Small fix workflows using old cypress results path

.github/workflows/RunE2EModernClient.yml
---
Fix the wrong step indentation in the workflow.
=> Fix RunE2EModernClient.yml wrong step indentation

packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery.scss, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml
---
Fix small CSS bug on gallery widget
=> [WC-2494]: fix small css bug on gallery widget

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-design-properties.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-filters.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_date-picker.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_drop-down-sort.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery-design-properties.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_tree-node-design-properties.scss
---
Using css variables instead of scss vars for values already set from atlas.
=> [WC-2483] :use css variables for data-widgets modules

packages/modules/data-widgets/CHANGELOG.md
=> fix: changelog for data-widget release

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/package.xml, pnpm-lock.yaml
=> [WC-2541] update tiny mce package version

packages/pluggableWidgets/timeline-web/CHANGELOG.md, packages/pluggableWidgets/timeline-web/package.json, packages/pluggableWidgets/timeline-web/src/Timeline.editorConfig.ts, packages/pluggableWidgets/timeline-web/src/Timeline.editorPreview.tsx, packages/pluggableWidgets/timeline-web/src/Timeline.tsx, packages/pluggableWidgets/timeline-web/src/__tests__/Timeline.spec.tsx, packages/pluggableWidgets/timeline-web/src/__tests__/__snapshots__/Timeline.spec.tsx.snap, packages/pluggableWidgets/timeline-web/src/components/TimelineComponent.tsx, packages/pluggableWidgets/timeline-web/src/components/__tests__/TimelineComponent.spec.tsx, packages/pluggableWidgets/timeline-web/src/helpers/grouping.ts, packages/pluggableWidgets/timeline-web/src/helpers/types.ts, packages/pluggableWidgets/timeline-web/src/helpers/useBasicItems.ts, packages/pluggableWidgets/timeline-web/src/helpers/useCustomItems.ts, packages/pluggableWidgets/timeline-web/src/hocs/withBasicItems.tsx, packages/pluggableWidgets/timeline-web/src/hocs/withCustomItems.tsx, packages/pluggableWidgets/timeline-web/src/package.xml
---
Add missing dependencies to re-render when data are changed.
=> [WC-2495] Timeline fix

packages/pluggableWidgets/barcode-scanner-web/CHANGELOG.md, packages/pluggableWidgets/barcode-scanner-web/package.json, packages/pluggableWidgets/barcode-scanner-web/src/components/BarcodeScanner.tsx, packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts, packages/pluggableWidgets/barcode-scanner-web/src/package.xml
---
Currently an issue exists where the module won't load because the reference to the canvas it needs is undefined. This PR changes this reference from a state to a ref, which ensures the reference can be found in the async process.
If the camera view appears with crop enabled, it means the canvas reference is not undefined, so the issue is fixed. While this shouldn't impact other features in the widget, it would be good to double-check they all work so we won't have to unpublish the widget again.
=> [WC-2535]: Fix barcodescanner error on module load

.github/workflows/RunE2ERCNightlies.yml, automation/run-e2e/docker/mxbuildRC.Dockerfile, automation/run-e2e/docker/mxruntimeRC.Dockerfile
---
Update docker files for the RC testing.
RC testing Github workflow should work.
=> [WC-1657] Update docker files for the RC testing

packages/shared/charts/src/rollup/shared-libs-config.cts
---
Add tarser plugin to shared charts to reduce plotly bundle size. This change makes resulting mpk way smaller.
- Build Charts.mpk from this branch. The restulting mpk should have smaller size then mpk v5.0.0
=> [WC-2537] chore(shared-charts): add code minification

packages/pluggableWidgets/charts-web/CHANGELOG.md, packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml
=> chore: prepare charts release

packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/AssociationFilter.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/FilterComponent.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/__tests__/FilterComponent.spec.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/features/referenceFilter.ts, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml
=> [WC-2504]: onchange event not working for association filter

packages/modules/data-widgets/package.json
=> chore(data-widgets): prepare release data-widgets-v2.21.1

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/src/__tests__/RichText.spec.tsx, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
---
sandbox_iframes property was being added before for security protection.
but this is also limiting users to have embedded media file from external sites.
Thus, with this PR, users allowed to turned off their sandbox iframes environment, as long they are aware of it.
=> [WC-2538] allow turned off sandbox iframes

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/package.xml
This PR meant to keep combobox v 2.0 separate from mainline.
due to: combobox 2.0 have Studio Pro min version 10.7
=> Combobox V2.0

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/features/data-export/DSExportRequest.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
---
Fix unexpected behaviour where unavailable data was stopping export execution
=> [WC-2567]: fix broken dg2 export when trying to export unavailable data

packages/modules/data-widgets/package.json
=> chore: bump data-widgets patch version

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/helpers/Static/StaticOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/datasourceFilter.ts, packages/pluggableWidgets/combobox-web/src/helpers/utils.ts, packages/pluggableWidgets/combobox-web/src/package.xml, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
---
We split "Contains" filterType into `Contains (fuzzy)` and `Contains (exact)`.
Current behavior will remain in `Contains (fuzzy)` option, 
`Contains (exact)` option will add a new "more strict" match option.
=> [WC-2555]: Combobox Filter Type

packages/pluggableWidgets/combobox-web/CHANGELOG.md
=> chore(combobox): update changelog

packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/package.xml
---
Fix missing style property.
=> [WC-2615] Gallery widget missing style props

packages/modules/data-widgets/package.json
---
Bumping version to release new data widgets version.
=> chore(data-widgets): prepare release data-widgets-v2.21.4

packages/pluggableWidgets/popup-menu-web/CHANGELOG.md, packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.editorConfig.ts, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.xml, packages/pluggableWidgets/popup-menu-web/src/__tests__/Menu.spec.ts, packages/pluggableWidgets/popup-menu-web/src/__tests__/PopupMenu.spec.ts, packages/pluggableWidgets/popup-menu-web/src/components/PopupMenu.tsx, packages/pluggableWidgets/popup-menu-web/src/package.xml, packages/pluggableWidgets/popup-menu-web/typings/PopupMenuProps.d.ts
---
We added a new "Close on" property to set the closing behavior of the popup when it is set to "Open on -> hover".
Default behavior for this was to close on click outside the popup, now the default is "hover leave"
=> [WC-2583]: Popup Hover leave 

packages/pluggableWidgets/html-element-web/CHANGELOG.md, packages/pluggableWidgets/html-element-web/package.json, packages/pluggableWidgets/html-element-web/src/package.xml, pnpm-lock.yaml
---
Updated dompurify library to prevent the security issue reported.
The widget should work as before.
=> [WC-2621] Update dompurify library to prevent the security issue

packages/pluggableWidgets/barcode-scanner-web/CHANGELOG.md, packages/pluggableWidgets/barcode-scanner-web/package.json, packages/pluggableWidgets/barcode-scanner-web/src/components/utils.tsx, packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts, packages/pluggableWidgets/barcode-scanner-web/src/package.xml
---
This PR fixes an issue in the barcode scanner. If you have the crop enabled, and change between portrait and landscape while scanning, it stops being able to scan. This PR also refactors the cropping and manual scanning code, and moves it to a separate file.
During testing, the cropping should be started in portrait, then switched to landscape and vice versa. After this, scanning should still work as expected
Normal scanning should also not be effected by the changes.
=> [WC-2542]: Fix issue with barcodescanner when changing between portrait and landscape mode

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/dropdown-sort-web/CHANGELOG.md, packages/pluggableWidgets/dropdown-sort-web/package.json, packages/pluggableWidgets/dropdown-sort-web/src/package.xml, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml
---
Prepare data-widgets 2.22 release
=> chore: prepare data widgets 2.22 release

.github/workflows/BuildJobs.yml, .github/workflows/ClearActionsCaches.yml, .github/workflows/CreateGitHubRelease.yml, automation/run-e2e/lib/docker-utils.mjs
---
Add mxtools build and cache steps to pipleline.
=> test: add cache for mxtools

packages/pluggableWidgets/datagrid-date-filter-web/e2e/DataGridDateFilter.spec.js, packages/pluggableWidgets/datagrid-dropdown-filter-web/e2e/DataGridDropDownFilter.spec.js, packages/pluggableWidgets/datagrid-number-filter-web/e2e/DataGridNumberFilter.spec.js, packages/pluggableWidgets/datagrid-text-filter-web/e2e/DataGridTextFilter.spec.js, packages/pluggableWidgets/datagrid-web/e2e/DataGrid.spec.js, packages/pluggableWidgets/datagrid-web/e2e/DataGridSelection.spec.js, packages/pluggableWidgets/dropdown-sort-web/e2e/DropDownSort.spec.js, packages/pluggableWidgets/gallery-web/e2e/Gallery.spec.js, packages/pluggableWidgets/gallery-web/e2e/GallerySelection.spec.js, packages/pluggableWidgets/tree-node-web/e2e/TreeNode.spec.js
---
Remove disabled rules from axe-core config in the data widgets e2e.
A11y checks and e2e should pass.
=> [WC-2644] Remove disabled rules from axe-core config in the data widgets e2e

packages/pluggableWidgets/pie-doughnut-chart-web/CHANGELOG.md, packages/pluggableWidgets/pie-doughnut-chart-web/package.json, packages/pluggableWidgets/pie-doughnut-chart-web/src/hooks/data.ts, packages/pluggableWidgets/pie-doughnut-chart-web/src/package.xml, packages/shared/charts/src/components/ChartView.tsx
---
Fix an issue where pie chart doesn't perform on click event due to an item index missing.
=> [WC-2561]: Fix issue with pie chart on click event

packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml
=> [WC2561]: bump version for charts-web

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/helpers/state/column/ColumnFilterStore.tsx, packages/pluggableWidgets/datagrid-web/src/helpers/state/column/ColumnStore.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, pnpm-lock.yaml
---
Reverting changes introduced in [WC-2553](https://github.com/mendix/web-widgets/pull/1220) for 9.24.
This will be the separate merge for 9.24 supported data widgets
[WC-2553]: https://mendix.atlassian.net/browse/WC-2553?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WC-2651]: Revert reference set support for Datagrid in SP 9.24

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json
=> fix: version

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/package.json
=> chore(data-widget): update min version

.github/workflows/BuildJobs.yml, .github/workflows/ClearActionsCaches.yml, .github/workflows/CreateMxtoolsCache.yml
---
Adjust pipeline after changes introduced in #1212 
This PR tries to fix this casse:
As you can see we have a lot of mxtools cache duplicats. This is due to how cache scope works. Here is the image that explains it:
So, this PR removes cache saving in Build jobs and instead use separate workflow to build and cache required images.
=> fix: stop caching mxtools on PR branches

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/helpers/Database/BaseDatabaseSingleSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseMultiSelectionSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/utils.ts, packages/pluggableWidgets/combobox-web/src/package.xml, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
=> [WC-2638]: Fix combobox issue not triggering onChange event

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/BaseDatasourceOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/hooks/useLazyLoading.ts
---
Added a new dependency to track if the datasource is defined or not between read-only state toggling, in order to trigger data refresh in combobox and prevent seeing empty list even though there should be values available.
Test cases both for WC-2640 and WC-2633 should be fixed.
=> [WC-2640] combobox data refresh

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/components/NumberFilterContainer.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/components/TextFilterContainer.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, packages/shared/widget-plugin-external-events/src/hooks.ts, packages/shared/widget-plugin-external-events/src/hooks/useOnSetValueEvent.ts, packages/shared/widget-plugin-filtering/src/controllers/EditableFilterController.ts, packages/shared/widget-plugin-filtering/src/controllers/NumberFilterController.ts, packages/shared/widget-plugin-filtering/src/controllers/StringFilterController.ts, packages/shared/widget-plugin-filtering/src/helpers/useNumberFilterController.ts, packages/shared/widget-plugin-filtering/src/helpers/useStringFilterController.ts
---
Fixes Reset All filter not working in DG2.
=> [WC-2648]: Fix filter reset

sigrid-metadata.yaml
=> chore: add sigrid metadata

packages/pluggableWidgets/google-tag-web/CHANGELOG.md, packages/pluggableWidgets/google-tag-web/package.json, packages/pluggableWidgets/google-tag-web/src/package.xml
=> [WC-2658]google-tag: update changelog and version

packages/customWidgets/any-chart-web/CHANGELOG.md, packages/customWidgets/any-chart-web/package.json, packages/customWidgets/any-chart-web/webpack.config.js, pnpm-lock.yaml
---
- Updated plotly to version 2.35.2; 
- Changed publicPath to avoid errors when using subpath in the app;
- Updated icons.
=> [WC-2690] Any charts: update plotly.js and other fixes

packages/modules/anychart-buildingblocks/package.json
---
Bump module version to release new charts version.
=> Prepare anycharts 3.0.4 release

packages/customWidgets/any-chart-web/package.json, pnpm-lock.yaml
---
Update webpack version of any charts widget to avoid errors in the build, which is getting a different version from pwc.
=> [Anycharts] Update the webpack version to avoid conflicts

packages/pluggableWidgets/range-slider-web/src/utils/useNumber.ts, packages/pluggableWidgets/slider-web/src/utils/useNumber.ts
---
@types/big.js@6.2.1 reworked exports. This caused issue with `instanceof`. Fixed by changing import statement.
=> chore: fix issue with big.js tyepes

packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/helpers/useRootGalleryStore.ts, packages/pluggableWidgets/gallery-web/src/package.xml
---
Added a setFilter method to have properly filtered with the initial default filter value.
=> [WC-2667]: Gallery default filter value fix

packages/pluggableWidgets/area-chart-web/CHANGELOG.md, packages/pluggableWidgets/area-chart-web/package.json, packages/pluggableWidgets/area-chart-web/src/package.xml, packages/pluggableWidgets/bar-chart-web/CHANGELOG.md, packages/pluggableWidgets/bar-chart-web/package.json, packages/pluggableWidgets/bar-chart-web/src/package.xml, packages/pluggableWidgets/bubble-chart-web/CHANGELOG.md, packages/pluggableWidgets/bubble-chart-web/package.json, packages/pluggableWidgets/bubble-chart-web/src/package.xml, packages/pluggableWidgets/chart-playground-web/CHANGELOG.md, packages/pluggableWidgets/chart-playground-web/package.json, packages/pluggableWidgets/chart-playground-web/src/package.xml, packages/pluggableWidgets/charts-web/CHANGELOG.md, packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml, packages/pluggableWidgets/column-chart-web/CHANGELOG.md, packages/pluggableWidgets/column-chart-web/package.json, packages/pluggableWidgets/column-chart-web/src/package.xml, packages/pluggableWidgets/heatmap-chart-web/CHANGELOG.md, packages/pluggableWidgets/heatmap-chart-web/package.json, packages/pluggableWidgets/heatmap-chart-web/src/package.xml, packages/pluggableWidgets/line-chart-web/CHANGELOG.md, packages/pluggableWidgets/line-chart-web/package.json, packages/pluggableWidgets/line-chart-web/src/package.xml, packages/pluggableWidgets/pie-doughnut-chart-web/CHANGELOG.md, packages/pluggableWidgets/pie-doughnut-chart-web/package.json, packages/pluggableWidgets/pie-doughnut-chart-web/src/package.xml, packages/pluggableWidgets/time-series-chart-web/CHANGELOG.md, packages/pluggableWidgets/time-series-chart-web/package.json, packages/pluggableWidgets/time-series-chart-web/src/package.xml
---
Update changelog and bump version to release charts-web 5.1.0.
=> Prepare charts 5.1.0 release

packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/typings/StringPrototypeReplaceAll.d.ts, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-web/package.json, pnpm-lock.yaml
---
**"string.prototype.replaceall"** is a pollyfil that we don't need anymore
**"deep-equal"** also is not being used.
this 2 package seems to have a lot of dependency tree scanned in snyk. 
Thus, if not being used, let's remove it.
=> chore(datagrid): remove unused imports

packages/pluggableWidgets/rich-text-web/CHANGELOG.md
=> fix: rte-changelog

packages/pluggableWidgets/tooltip-web/CHANGELOG.md, packages/pluggableWidgets/tooltip-web/package.json, packages/pluggableWidgets/tooltip-web/src/Tooltip.editorConfig.ts, packages/pluggableWidgets/tooltip-web/src/components/Tooltip.tsx, packages/pluggableWidgets/tooltip-web/src/components/__tests__/Tooltip.spec.tsx, packages/pluggableWidgets/tooltip-web/src/components/__tests__/__snapshots__/Tooltip.spec.tsx.snap, packages/pluggableWidgets/tooltip-web/src/package.xml, packages/pluggableWidgets/tooltip-web/src/ui/Tooltip.scss, packages/pluggableWidgets/tooltip-web/src/utils/useFloatingUI.ts, pnpm-lock.yaml
---
Fix issue on tooltip-web with hover, where the tooltip flicker.
=> [WC-2682]: fix tooltip flickering

packages/pluggableWidgets/datagrid-web/rollup.config.js
---
Fix issue with react/jsx-runtime in design preview
=> [WC-2707] fix design preview for datagrid

packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/StaticFilterContainer.tsx, packages/shared/widget-plugin-filtering/src/controllers/NumberFilterController.ts, packages/shared/widget-plugin-filtering/src/controllers/StaticFilterController.ts, packages/shared/widget-plugin-filtering/src/controllers/StringFilterController.ts
---
Additional PR for Reset all filters fix.
=> [WC-2648]: Dropdown set filter

packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml
=> chore(data-widget): update version for release

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx, packages/pluggableWidgets/gallery-web/src/package.xml
=> Fix rendering in design mode

packages/pluggableWidgets/tree-node-web/CHANGELOG.md, packages/pluggableWidgets/tree-node-web/package.json, packages/pluggableWidgets/tree-node-web/src/TreeNode.tsx, packages/pluggableWidgets/tree-node-web/src/package.xml
---
Tree node retrieved it's items from `datasource.items` directly.
This fix creates a localstate for TreeNodeItem, and prevent it to change state while datasource is loading.
Thus, maintain the collapse/uncollapse state.
=> [WC-2699] prevent treenode to reset items data while loading

packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml, packages/shared/widget-plugin-filtering/package.json, packages/shared/widget-plugin-filtering/src/controllers/NumberFilterController.ts, packages/shared/widget-plugin-filtering/src/controllers/StringFilterController.ts, packages/shared/widget-plugin-filtering/src/helpers/useBasicSync.ts
=> [WC-2680] onChange not trigger on empty or not empty filter

packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/RefFilterContainer.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml, packages/shared/widget-plugin-filtering/src/controllers/RefFilterController.ts
---
value have to set to guid, which supported by nanoflow
something like this:
or for multi select,
use NPE templist to get guid and reduce it to comma separated string.
=> [WC-2710] allow set reference filter value

packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx, packages/shared/widget-plugin-filtering/src/controls.ts, packages/shared/widget-plugin-filtering/src/controls/input/InputWithFilters.tsx
=> [WC-2716] datagrid design preview static rendering

packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/shared/widget-plugin-filtering/src/errors.ts, packages/shared/widget-plugin-filtering/src/helpers/useDateFilterAPI.ts, packages/shared/widget-plugin-filtering/src/helpers/useNumberFilterAPI.ts, packages/shared/widget-plugin-filtering/src/helpers/useSelectFilterAPI.ts, packages/shared/widget-plugin-filtering/src/helpers/useStringFilterAPI.ts
=> fix: clearer type mismatch error message

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml
=> Data Widgets v2.28.0

packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml
=> fix: changelog and versioning data widgets

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseValuesProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/Preview/DatabasePreviewSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/utils.ts, packages/pluggableWidgets/combobox-web/src/package.xml
=> [WC-2714] combobox database custom content and value attribute runtime error

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-filters.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss
=> [WC-2736]fix: css var get overwrite by datagrid

packages/modules/data-widgets/CHANGELOG.md
=> fix: changelog data widget

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseSingleSelectionSelector.ts
---
onchanged triggered directly onload even though there is no data.
=> [WC-2750] fix: combobox infinite load when initial value triggered onchange

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/package.xml
=> [WC-2753]fix: placeholder not shown

packages/modules/data-widgets/package.json
=> update data-widgets patch version

packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml, packages/pluggableWidgets/pie-doughnut-chart-web/CHANGELOG.md, packages/pluggableWidgets/pie-doughnut-chart-web/package.json, packages/pluggableWidgets/pie-doughnut-chart-web/src/PieChart.xml, packages/pluggableWidgets/pie-doughnut-chart-web/src/__tests__/PieChart.spec.tsx, packages/pluggableWidgets/pie-doughnut-chart-web/src/hooks/data.ts, packages/pluggableWidgets/pie-doughnut-chart-web/src/package.xml, packages/pluggableWidgets/pie-doughnut-chart-web/typings/PieChartProps.d.ts, packages/shared/charts/src/components/ChartView.tsx, packages/shared/charts/src/components/types.ts
=> [WC-2440]: pie chart issue

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/EditorWrapper.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/src/utils/customPluginRegisters.ts, packages/pluggableWidgets/rich-text-web/src/utils/formats/button.ts
=> [WC-2734] [WC-2743] rich text update

packages/pluggableWidgets/popup-menu-web/CHANGELOG.md, packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/PopupMenu.xml, packages/pluggableWidgets/popup-menu-web/src/package.xml
---
Setting the trigger element is now required to prevent rendering errors.
=> [WC-2747]: Popup menu: make trigger element required

packages/pluggableWidgets/any-chart-web/package.json, packages/pluggableWidgets/any-chart-web/src/AnyChart.tsx, packages/pluggableWidgets/any-chart-web/src/components/PlotlyChart.ts, packages/pluggableWidgets/any-chart-web/src/types/plotly.js-dist.d.ts, packages/pluggableWidgets/any-chart-web/src/utils/ChartDataProcessor.ts, pnpm-lock.yaml
---
Implemented chart widget with plot.ly for the Anychart spike, props passed are used and sizing works well.
=> [WC-2674]: Pluggable Anychart

packages/customWidgets/signature-web/package.json
=> chore: update signature web script

.github/workflows/CreateGitHubRelease.yml, .github/workflows/PublishMarketplace.yml, automation/utils/bin/rui-publish-marketplace.ts, automation/utils/src/api/contributor.ts, automation/utils/src/package-info.ts, packages/pluggableWidgets/rich-text-web/package.json
update react client ready flag and publishing user to srv-widgets@mendix.com
pipeline can be ignored
=> [WC-2558] update react client ready flag and publishing user

automation/utils/src/api/contributor.ts, automation/utils/src/package-info.ts
=> fix: pipeline

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
=> fix: position of paging button on datagrid

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/package.xml
=> chore(combobox): update changelog and version

.github/workflows/RunE2ENightly.yml
---
This change replaces the Firefox e2e workflow for the nightly build execution. It aims to prevent unnoticed changes in the GitHub environment that could impact the e2e process(screenshot test) within the branches' workflow.
=> Replace the e2e Firefox workflow for the nightly build.

.github/workflows/BuildJobs.yml, .github/workflows/CreateMxtoolsCache.yml
---
The action cache used in some workflows began sending warnings related to its deprecation in March 2025. This change updates the action to ensure the cache continues working.
More details:
https://github.blog/changelog/2024-12-05-notice-of-upcoming-releases-and-breaking-changes-for-github-actions/#actions-cache-v1-v2-and-actions-toolkit-cache-package-closing-down
https://github.com/actions/cache/releases/tag/v4.2.0
=> Update action cache deprecated

packages/modules/data-widgets/package.json, pnpm-lock.yaml
---
Update xlsx to latest version.
=> []: data-widgets update xlsx to v0.20.3

.github/workflows/RunE2EModernClient.yml
---
Small fix for missing playwright browser installation.
=> Small fix for missing playwright browser installation

packages/pluggableWidgets/accordion-web/CHANGELOG.md, packages/pluggableWidgets/accordion-web/package.json, packages/pluggableWidgets/accordion-web/src/Accordion.tsx, packages/pluggableWidgets/accordion-web/src/components/Accordion.tsx, packages/pluggableWidgets/accordion-web/src/components/__tests__/__snapshots__/Accordion.spec.tsx.snap, packages/pluggableWidgets/accordion-web/src/package.xml, packages/pluggableWidgets/accordion-web/src/utils/reducers.ts
=> [WC-2762] accordion state animation fix

packages/pluggableWidgets/popup-menu-web/CHANGELOG.md, packages/pluggableWidgets/popup-menu-web/package.json, packages/pluggableWidgets/popup-menu-web/src/components/PopupTrigger.tsx, packages/pluggableWidgets/popup-menu-web/src/package.xml
---
Added a stopPropagation to reference element onClick. 
When reference element is overlaying other items it shouldn't allow click event to propagate.
Can be tested with test project here: [WC-2836](https://mendix.atlassian.net/jira/software/c/projects/WC/issues/WC-2836?jql=project%20%3D%20%22WC%22%20ORDER%20BY%20created%20DESC)
[WC-2836]: https://mendix.atlassian.net/browse/WC-2836?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> [WC-2836]: Handle reference element on click

packages/modules/data-widgets/package.json, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/components/Grid.tsx, packages/pluggableWidgets/datagrid-web/src/components/GridBody.tsx, packages/pluggableWidgets/datagrid-web/src/components/GridHeader.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap
---
Change back to CSS grid layout that dictates size for header and body.
=> fix(datagrid-web): fallback to previous css layout

packages/pluggableWidgets/datagrid-web/CHANGELOG.md
=> chore: update changelog (dg)

packages/pluggableWidgets/file-uploader-web/CHANGELOG.md, packages/pluggableWidgets/file-uploader-web/package.json, packages/pluggableWidgets/file-uploader-web/src/components/FileEntry.tsx, packages/pluggableWidgets/file-uploader-web/src/package.xml, packages/pluggableWidgets/file-uploader-web/src/ui/FileUploader.scss
Hide long filenames with ellipsis...
=> [WC-2843] Fix long filenames in File uploader 

automation/run-e2e/docker/mxbuild.Dockerfile, automation/run-e2e/docker/mxbuildRC.Dockerfile, automation/run-e2e/docker/mxruntime.Dockerfile, automation/run-e2e/docker/mxruntimeRC.Dockerfile
---
Update java to 21 in the dockerfile.
=> Update java to 21 in the dockerfile

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss
=> [WC-2855] fix: right aligned content styling

packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/components/EditorWrapper.tsx
=> fix: rte make sure to update only once

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/components/EditorWrapper.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/src/utils/MxQuill.ts
=> fix: blank space accidentally shown in between formats

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/__tests__/RefreshController.spec.ts, packages/pluggableWidgets/datagrid-web/src/controllers/RefreshController.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/RootGridStore.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
---
Fixed refresh interval to use seconds instead of ms.
Set a refresh interval in the DataGrid 2 and verify in the network request if the calls are made at the intervals configured in the widget.
=> [WC-2872] Fixed refresh interval to use seconds instead of ms

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/StaticSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/package.xml, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
---
Change Aria required to expression.
=> [WC-2396] Combobox aria required

packages/pluggableWidgets/dropdown-sort-web/CHANGELOG.md, packages/pluggableWidgets/dropdown-sort-web/package.json, packages/pluggableWidgets/dropdown-sort-web/src/components/SortComponent.tsx, packages/pluggableWidgets/dropdown-sort-web/src/components/__test__/__snapshots__/DropdownSort.spec.tsx.snap, packages/pluggableWidgets/dropdown-sort-web/src/components/__test__/__snapshots__/SortComponent.spec.tsx.snap, packages/pluggableWidgets/dropdown-sort-web/src/package.xml
---
The read-only attribute is set incorrectly, causing a grey background from the read-only input style.
=> [WC-2899] Fix wrong read-only style

packages/modules/data-widgets/package.json
---
Bump data widgets version to release dropdown sort fix.
=> Data widgets bump version to 2.30.4

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
=> [WC-2891] fix: missing toolbar component

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json
This reverts commit 3ff6f9ba1f74a706e56fbedc22ff671b7c61564a.
---
=> Revert "chore(data-widget): update min version"

packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-dropdown-filter.scss, packages/pluggableWidgets/datagrid-dropdown-filter-web/e2e/DataGridDropDownFilter.spec.js, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/components/__tests__/__snapshots__/DataGridDropdownFilter.spec.tsx.snap, packages/shared/widget-plugin-filtering/src/controllers/picker/mixins/TagPickerControllerMixin.ts, packages/shared/widget-plugin-filtering/src/controls/combobox/Combobox.tsx, packages/shared/widget-plugin-filtering/src/controls/select/Select.tsx, packages/shared/widget-plugin-filtering/src/controls/tag-picker/TagPicker.tsx
---
Inconsistent behavior on dropdown filter with text selected items. It should have ellipsis but it was behaving like labels instead.
=> [WC-2865]: Inconsistent Filter Behavior

packages/pluggableWidgets/calendar-web/src/__tests__/__snapshots__/Calendar.spec.tsx.snap
=> fix: calendar test

packages/pluggableWidgets/rich-text-web/src/components/CustomToolbars/useEmbedModal.ts, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/utils/formats/quill-table-better/assets/css/quill-table-better.scss, packages/pluggableWidgets/rich-text-web/src/utils/helpers.ts
---
Replace setContents with updateContents for consistency in Quill
=> [WC-2835]fix(rich-text-web): replace setContents with updateContents

automation/run-e2e/lib/update-test-project.mjs
---
Lock atlas core v3 version, since we released Atlas v4 which broke the e2e.
=> Lock atlas core v3 version

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/__tests__/__snapshots__/RichText.spec.tsx.snap, packages/pluggableWidgets/rich-text-web/src/components/EditorWrapper.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml
---
Changed the word count indicator. Old version displayed "0 word" which should be "0 words". Only when wordCount == 1 should it say "word"
=> Change word count to account for 0

packages/pluggableWidgets/custom-chart-web/CHANGELOG.md, packages/pluggableWidgets/custom-chart-web/package.json, packages/pluggableWidgets/custom-chart-web/src/controllers/ChartPropsController.ts, packages/pluggableWidgets/custom-chart-web/src/package.xml
---
We have size configuration for some elements of the custom chart, this pr adds conditional logic for size handling given for the layout of the chart, therefore if user does apply configuration to those "size handled" properties, they will be able override and use their own values.
=> [WC-2920]: Custom Chart config override

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseSingleSelectionSelector.ts
=> [WC-2923] fix combobox selection not trigger on null value set

packages/pluggableWidgets/video-player-web/CHANGELOG.md, packages/pluggableWidgets/video-player-web/package.json, packages/pluggableWidgets/video-player-web/src/VideoPlayer.tsx, packages/pluggableWidgets/video-player-web/src/VideoPlayer.xml, packages/pluggableWidgets/video-player-web/src/components/Dailymotion.tsx, packages/pluggableWidgets/video-player-web/src/components/Html5.tsx, packages/pluggableWidgets/video-player-web/src/components/Video.tsx, packages/pluggableWidgets/video-player-web/src/components/Vimeo.tsx, packages/pluggableWidgets/video-player-web/src/components/Youtube.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Dailymotion.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Html5.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/SizeContainer.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Video.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Vimeo.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/Youtube.spec.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Dailymotion.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Html5.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/SizeContainer.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Video.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Vimeo.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Youtube.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/package.xml, packages/pluggableWidgets/video-player-web/typings/VideoPlayerProps.d.ts, pnpm-lock.yaml
---
Add Title property under Accessibility tab. Also rewrite tests to RTL
=> [WC-2724] Add title property for video player

package.json, packages/pluggableWidgets/calendar-web/package.json, packages/pluggableWidgets/calendar-web/src/Calendar.tsx, packages/pluggableWidgets/calendar-web/src/Calendar.xml, packages/pluggableWidgets/calendar-web/src/__tests__/__snapshots__/Calendar.spec.tsx.snap, packages/pluggableWidgets/calendar-web/src/utils/calendar-utils.ts, packages/pluggableWidgets/calendar-web/typings/CalendarProps.d.ts, pnpm-lock.yaml
---
Action variables!
A small guide to test with action variables (although I'm going to add a test project): 
Configure events of the calendar widget, ex;
- On click
- Set a microflow
- Microflow settings -> Add a parameter from the entity you've created for the Events (startDate,endDate,allDay etc.)
- Click on the parameter you've just added and set its expression.
If you go to the microflow you've selected, you'll see it has the parameters added in the flow now. Voila!
=> [WC-2792]: Calendar actions & events

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/package.json
=> [WC-3011]Releasing Data Widgets 3.0

packages/pluggableWidgets/file-uploader-web/CHANGELOG.md, packages/pluggableWidgets/file-uploader-web/package.json, packages/pluggableWidgets/file-uploader-web/src/package.xml, packages/pluggableWidgets/file-uploader-web/src/stores/FileStore.ts, packages/pluggableWidgets/file-uploader-web/src/utils/mx-data.ts
=> [WC-3002] fix file uploader image thumbnail issue

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml
=> chore: data widget prepare release patch

turbo.json
---
Since turbo v2 the env mode is strict by default. With that, the process.env wasn't passed to the child process. Added a [globalPassThroughEnv](https://turborepo.com/docs/reference/configuration#globalpassthroughenv) configuration in the `turbo.json` file to avoid the missing env variable in the e2e and release automation.
=> Add turbo globalPassThroughEnv

packages/modules/data-widgets/package.json
---
Fix data-widgets filter missing prefix scope.
=> Fix data-widgets filter missing prefix scope

packages/modules/data-widgets/package.json, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml
=> Prepare Data widgets 3.1

.github/workflows/PublishMarketplace.yml
=> Fix add missing gh token

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/helpers/state/GridPersonalizationStore.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
---
Fix unexpected restore of previously saved filters
=> [WC-3041] Don't restore filter settings if disabled in config

packages/pluggableWidgets/combobox-web/SiemensMendixComboBox__2.5.0__READMEOSS_2025-08-12__04-04-29.html, packages/pluggableWidgets/events-web/SiemensMendixEvents__1.1.0__READMEOSS_2025-08-12__04-00-11.html, packages/pluggableWidgets/events-web/package.json, packages/pluggableWidgets/events-web/src/package.xml, packages/shared/rollup-web-widgets/copyFiles.mjs
=> Events release

packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/src/components/DatePicker.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/__snapshots__/DatagridDateFilter.spec.tsx.snap, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/__snapshots__/DatePicker.spec.tsx.snap, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/__snapshots__/FilterComponent.spec.tsx.snap, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/src/components/__tests__/__snapshots__/DatagridNumberFilter.spec.tsx.snap, packages/pluggableWidgets/datagrid-text-filter-web/src/components/__tests__/__snapshots__/DatagridTextFilter.spec.tsx.snap, packages/shared/widget-plugin-dropdown-filter/src/controls/combobox/Combobox.tsx, packages/shared/widget-plugin-dropdown-filter/src/controls/select/Select.tsx, packages/shared/widget-plugin-dropdown-filter/src/controls/tag-picker/TagPicker.tsx, packages/shared/widget-plugin-filtering/src/controls/input/InputWithFilters.tsx
---
A11y improvements. This changes fix issues reported by Axe devtools v4.111
=> [WC-2754] datagrid Axe issues fix

package.json, packages/pluggableWidgets/custom-chart-web/CHANGELOG.md, packages/pluggableWidgets/custom-chart-web/package.json, packages/pluggableWidgets/custom-chart-web/src/controllers/ChartPropsController.ts, packages/pluggableWidgets/custom-chart-web/src/hooks/useCustomChart.ts, packages/pluggableWidgets/custom-chart-web/src/package.xml, pnpm-lock.yaml
---
Bug fix to set eventDataAttribute properly.
setting eventDataAttribute on onClick action, see the test project.
=> [WC-3061]: Custom charts set event data attribute 

packages/pluggableWidgets/combobox-web/SiemensMendixComboBox__2.6.0__READMEOSS_2025-09-26__06-48-06.html, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/package.xml
=> chore: prepare combobox release
