turbo.json
TLDR, This changes will make sure that our CI cache is invalidated whenever we update `release-utils-internal`.
If you wan't to know more, [hashing](https://turbo.build/repo/docs/core-concepts/caching#hashing) and [globalDependencies](https://turbo.build/repo/docs/reference/configuration#globalDependencies-1) docs are good place to start learning how turbo works;
=> Invalidate ci cache if release tools changed

packages/modules/web-actions/CHANGELOG.md
Current changelog use "module" format, but we switched to "widget" format, so changelog should be formatted accordingly 
-   [ ] Bug fix (non-breaking change …
=> [WC-1325] Fix changelog format (web-actions)

packages/shared/charts/src/hooks/usePlotChartDataSeries.ts
-   [x] Bug fix
-   [x] Feature
-   [ ] Refactor
Plotly allows for `null` in your data and will by default fill up gaps. It also has the option to set `connectgaps` to false so you can have a line with gaps in between.  https://plotly.com/javascript/line-charts/#connect-gaps-between-data
The code that this pull request removes prevents `null` ending up in your data set, even though plotly can handle this. Right now if you would have an empty value in your dataset the chart would not render. 
By removing this code, the chart will still render when you have an empty value in your data, by default it will connect the gaps and you will have to option to turn this off.
=> DB-1953 remove null check, because null values are a feature in plotly

packages/tools/release-utils-internal/bin/rui-changelog-helper.ts
If you run `pnpm run changelog` and choose `charts-web` this command will fail. Right now we have two changelog formats: `widget` and `module`. Widget format is simple and don't require extra effort to handle and maintain. Module format is bit complex and actually it's better to call this format as "composed changelog" as it tries to get all records from it's children (eg. in data-widgets and charts-web). So, `pnpm run changelog` tries to parse changelog with `widget` format, if it fails, then it tries to parse changelog with `module` format. The problem is that `charts-web`, is a widget, which uses `module` format for changelogs... yeah, I know. So, to not make things even more complex we now use generic function to parse package metadata, so we don't care what format is used for …
=> fix(release-utils-internal): use generic package info

package.json, packages/pluggableWidgets/charts-web/CHANGELOG.md, packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml, packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/src/ui/RichText.scss, pnpm-lock.yaml
Updated libraries:
- d3-color to v3.1.0
- ckeditor4 to v4.20.0
-   [x] Dependency changes (any modification to dependencies in `package.json`)
- RichText - need health check, just to make sure it loads and renders correctly
- Charts - health check, probably just run Atlas Design System app with updated widget
=> [WC-1416]: Update vulnerable dependencies

.github/workflows/Build.yml
This PR change how we store trubo cache on GH. Now cache should be saved only on `main` and updated when `main` SHA changes. That means we not storing cache for pull request branches anymore.
=> ci(build): keep turbo cache only on main

.github/workflows/Build.yml
Just small experimental optimization. 
turbo use concurrency = 10 by default, but initially we limited it for 4 on Linux and 1 on Windows to avoid Out of memory errors. Now I'm trying to increase concurrency and see how this will impact CI stability.
=> ci(build): increase task concurrency for turbo

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/html-element-web/CHANGELOG.md, packages/pluggableWidgets/html-element-web/package.json, packages/pluggableWidgets/html-element-web/src/HTMLElement.editorConfig.ts, packages/pluggableWidgets/html-element-web/src/package.xml, packages/shared/pluggable-widgets-commons/src/structure-preview-api/index.ts
-   [X] Added record to packages' CHANGELOG.md
-   [x] Bug fix (non-breaking change which fixes an issue)
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or …
=> [WC-1301]: update structure preview for data grid 2

packages/pluggableWidgets/timeline-web/CHANGELOG.md, packages/pluggableWidgets/timeline-web/package.json, packages/pluggableWidgets/timeline-web/src/Timeline.tsx, packages/pluggableWidgets/timeline-web/src/Timeline.xml, packages/pluggableWidgets/timeline-web/src/package.xml, packages/pluggableWidgets/timeline-web/src/utils/utils.ts, packages/pluggableWidgets/timeline-web/typings/TimelineProps.d.ts
Timeline widget with custom visualization and grouping set to "month" had issue where event that has same month, but different year will end up in same group. To prevent that we change default grouping method to also take year into account.
-   [x] Bug fix (non-breaking change which fixes an issue)
Expected `event1` with date `2022-12-01` to be in different group with `event2` with date `2019-12-31`
=> [WC-1361]: timeline grouping bug

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
-   [x] New feature (non-breaking change which adds functionality)
-   [ ] Breaking change (fix or …
=> [WC-1054]: refresh on interval for data grid 2

.github/workflows/Build.yml
This PR introduces new build step, to handle `pnpm install` step failure on dependabot PRs
This step is meant to update pnpm-lock.yaml file on Dependabot
pull requests. Right now dependabot not work fine with monorepos
so we have to do extra work to automatically update lock file.
This step is part of "check" job, but could be part of any other job.
We put it here just because previous `Install dependencies` step is just
first "install" in this workflow.
The idea of this step - if install fails, try to fix lock file, commit and
push changes.
NOTE: we use magic string ([dependabot skip]) to allow branch rebase, read more at link below.
https://docs.github.com/en/code-security/dependabot/working-with-dependabot/managing-pull-requests-for-dependency-updates#allowing-dependabot-to-rebase-and-f …
=> [WC-1550]: Handle pnpm install failure in dependabot PRs

.github/workflows/Build.yml
Small fix to resolve issue with branch in GH workflow:
```
> validate-staged-widget-versions
> node scripts/validation/validate-versions-staged-files.js
[detached HEAD 447659c7] build: update pnpm-lock.yaml [dependabot skip]
1 file changed, 4 insertions(+), 4 deletions(-)
fatal: You are not currently on a branch.
To push the history leading to the current (detached HEAD)
state now, use
git push origin HEAD:<name-of-remote-branch>
```
-   [ ] Breaking change (fix or feature that would cause existing functionality to …
=> ci: fix git issues on lock file update

.github/workflows/Build.yml, .github/workflows/UpdateLockFile.yml
This time we split lock file update into separate workflow. It seems that we need to grand `pull-request` write permissions. So, to not make `Build` workflow too heavy, and not break permissions, I decided to split this into separate workflow, that will be triggered only for dependabot PRs.
=> [WC-1550]: Add workflow to update lock file

packages/pluggableWidgets/html-element-web/CHANGELOG.md, packages/pluggableWidgets/html-element-web/src/utils/__tests__/style-utils.spec.ts, packages/pluggableWidgets/html-element-web/src/utils/style-utils.ts
Small change in regex that we use to split CSS rules. Now we allow zero spaces in CSS props. (e.g. "width:10px")
-   [x] Bug fix (non-breaking change which fixes an issue)
- Just create any html element widget and add style attribute with zero space properties.
=> [WC-1561]: Update style regex to handle zero spaces

automation/run-e2e/cypress.config.cjs, automation/run-e2e/lib/ci.mjs, automation/run-e2e/lib/docker-utils.mjs, automation/run-e2e/package.json, pnpm-lock.yaml, turbo.json
The main goal here is to update Cypress to version 12. Important note, since version 12 Cypress is enabling by default the testIsolation, that means all the tests are running in a clean state, in our case that affects our tests since we depend on some page content, to revert that I have disabled this testIsolation, so now it's behaving like before. 
We need to do a new analysis to see if we can follow this recommendation(https://docs.cypress.io/guides/references/migration-guide#Test-Isolation). I also uncommented one part of the code to get the correct Mendix version.
EXTRA: fix e2e hitting the turbo cache incorrectly.
-   [ …
=> Update to cypress 12

.github/workflows/BuildJobs.yml, automation/run-e2e/lib/ci.mjs, automation/run-e2e/lib/setup-test-project.mjs, automation/run-e2e/lib/utils.mjs
Add error logs on fetch failure
=> feat(run-e2e): authorize github api requests

packages/pluggableWidgets/maps-web/CHANGELOG.md
Fix the incorrect heading in the changelog file for the maps widget.
-   [ ] All new and existing tests passed
-   [ ] I run `lint` command locally and it doesn’t give errors
-   [ ] New feature …
=> Fix incorrect heading in the changelog file in the maps widget

packages/pluggableWidgets/color-picker-web/cypress/integration/ColorPicker.spec.js
Fix incorrect assertion in color picker Firefox e2e.
-   [ ] New feature (non-breaking change …
=> Fix incorrect assertion in color picker Firefox e2e

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/components/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/components/__tests__/RichText.spec.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
In the current version, there is a bug that when using conditional editability in widget settings and rendering the widget in read-only mode then it's not possible to switch to edit mode and the setValue will be failed.
This PR is to fix this issue.
-   [ ] No code changes (changes to documentation, CI, …
=> RichTextEditor fix conditianl editability and minor cleanup

automation/run-e2e/lib/ci.mjs, automation/run-e2e/lib/config.mjs, automation/run-e2e/lib/dev.mjs, automation/run-e2e/lib/setup-test-project.mjs, automation/run-e2e/lib/update-test-project.mjs, automation/run-e2e/lib/utils.mjs
Right now, when running e2e tests we downloading test project and then running `release` and then we copying mpk to downloaded test project. This case don't work with `data-widgets` as widgets may depend on changes that were made in datagrid itself. Also, there are might be changes related to styles. So, to bypass this limitation I added new option - `e2e-update-project` hook (script). Now, e2e will check presence of this hook (script) in `package.json` and will execute this hook (script) if hook is present.   
-   [x] New feature (non-breaking change which adds functionality)
-   [ …
=> feat(run-e2e): add e2e update project hook

packages/pluggableWidgets/rich-text-web/src/components/RichText.tsx
When using custom bar the underline option doesn't show up even if configured to show. This fix force the `removeButtons` configuration to blank, so none of the hardcoded button configs in the CKEditor will cause the issue anymore.
-   [ …
=> [WC-1536] Rich text custom bar underline

.github/workflows/Renovate.yml
Stop triggering renovate workflow when PR is labeled. It worked few times, but now it doesn't work, so it's better to disable it. We still can trigger workflow manually if we need to rebase some branches.
=> ci: stop triggering Renovate action when pr is labeled

packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/RichText.tsx, pnpm-lock.yaml
The current sanitize-html package is removing img tag used in the CKEditor. I have updated the package to use the dompurify as we're using in the HTMLElement widget.
Extra: Fixed incorrect config name being used for allowed content configuration.
-   [ ] No code changes (changes to documentation, CI, …
=> Rich text sanitization is removing img tag incorrectly

packages/pluggableWidgets/rich-text-web/src/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/components/MainEditor.tsx, packages/pluggableWidgets/rich-text-web/src/components/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/components/__tests__/RichText.spec.tsx, packages/pluggableWidgets/rich-text-web/src/components/__tests__/__snapshots__/RichText.spec.tsx.snap, packages/pluggableWidgets/rich-text-web/src/utils/ckeditorConfigs.ts
This is rewrite of `RichText.tsx`. I decided to switch to `React.Component` because it better suites prop update strategy in this case (only stringAttribute). Using `componentDidUpdate` in combination with event listeners management I was able to achieve good result. Now we can sync state with attribute, focus stays same and we don't override new passed attributes.
-   [ ] Added record to packages' CHANGELOG.md (TODO)
-   [ ] Bumped package version in `package.json` and `package.xml` (TODO)
-   [ ] Created docs PR to …
=> [WC-1626] RichText listen to widget fix

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml
Added a file size limit for pasting or dropping images, user is warned with a notification if the selected image(s) is exceeding the limit.
-   [X] All new and existing tests passed
-   [X] I run `lint` command locally and it doesn’t give errors
-   [X] PR title properly formatted `[XX-000]: description`
-   [X] Added record to packages' CHANGELOG.md
-   [X] Bumped package version in `package.json` and `package.xml`
-   [X] Bug fix (non-breaking change which fixes an issue)
-   [ ] Test …
=> [WC-1621]: Rich Text image upload performance drop

.github/pull_request_template.md
---
I propose new PR template as I think our current one still needs improvements.
Main changes:
1. Now template starts with instruction.
2. PR type section become the first section.
3. Remove all check box lists and "confirmations", so only needed information is visible.
---
=> chore(web-widgets): update pr template

packages/pluggableWidgets/image-web/CHANGELOG.md, packages/pluggableWidgets/image-web/package.json, packages/pluggableWidgets/image-web/src/Image.editorPreview.tsx, packages/pluggableWidgets/image-web/src/Image.tsx, packages/pluggableWidgets/image-web/src/components/Image/Image.tsx, packages/pluggableWidgets/image-web/src/components/Image/ui.tsx, packages/pluggableWidgets/image-web/src/components/__tests__/Image.spec.tsx, packages/pluggableWidgets/image-web/src/components/__tests__/__snapshots__/Image.spec.tsx.snap, packages/shared/pluggable-widgets-commons/src/structure-preview-api/index.ts
---
This PR adds support for icon collections (release as part of 9.24)
Page editor epic: https://mendix.atlassian.net/browse/PAG-2025
This particularly affects the usage of icons, but everything (image, image icon, custom icon, glyph icon) should be tested. Requires using Studio Pro with the feature flag `--enable-custom-icon-collections`. When it comes to testing, hit me up so I can provide you with a module with custom icons that you can simply import.
see description
=> feat(image-web): support icon collections

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/components/__tests__/__snapshots__/RichText.spec.tsx.snap, packages/pluggableWidgets/rich-text-web/src/package.xml
---
Fix issue with two widget with the same name putting same ID in the document.
=> [WC-1759]: fix id clash for widgets with the same name

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml
---
Don't re-init the editor when event props as onChange and onKeyPress change in props.
=> [WC-1776]: don't re-render on onChange or onKeyPress prop change

packages/pluggableWidgets/barcode-scanner-web/CHANGELOG.md, packages/pluggableWidgets/barcode-scanner-web/package.json, packages/pluggableWidgets/barcode-scanner-web/src/BarcodeScanner.tsx, packages/pluggableWidgets/barcode-scanner-web/src/components/BarcodeScanner.tsx, packages/pluggableWidgets/barcode-scanner-web/src/hooks/useReader.ts, packages/pluggableWidgets/barcode-scanner-web/src/package.xml, packages/pluggableWidgets/barcode-scanner-web/src/ui/BarcodeScanner.scss
---
- Adds a different scan method when the mask is enabled, this should only scan part of the screen instead of all. This improves scan accuracy for 1 dimensional codes in particular. 
- Changes implementation of Detect callback to always fire, since a datasource will always be attached but an event is not required. This causes the barcode scanner to 'fail' silently when first using it and having a datasource connected but no event set. 
---
- Non masked version of the widget should have no changes from current implementation (apart from Detect callback change), but the masked option should now have improved accuracy for 1 dimensional codes.
=> [WC-1763]: barcode scanner improvements

packages/pluggableWidgets/charts-web/CHANGELOG.md, packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml, packages/shared/charts/package.json, packages/shared/charts/src/hooks/usePlotChartDataSeries.ts
and
---
Previously, when some items had no data for grouping the chart was never displayed, this change introduces new `(empty)` group for those items and groups those items.
Charts display data in the situation while it wasn't previously.
=> [WC-1605]: group chart items where grouping value is not reachable as '(empty)'

packages/shared/pluggable-widgets-commons/src/components/web/InfiniteBody.tsx
Bug fix:
scrolling in Datagrid 2.
the issue occurs due to Math.Floor issue having problems with rounded integer, which could cause discrepancy in boolean comparison such as `2 === 1`
which resulting in fetch new page not triggered.
linked ticket: https://mendixsupport.zendesk.com/agent/tickets/167627
=> [WC-1349]: fix: scrolling on datagrid 2

packages/modules/google-tag/package.json, packages/modules/google-tag/src/javascriptsource/googletagmodule/actions/GoogleTagAction.js, packages/pluggableWidgets/google-tag-web/CHANGELOG.md, packages/pluggableWidgets/google-tag-web/package.json, packages/pluggableWidgets/google-tag-web/src/GoogleTag.xml, packages/pluggableWidgets/google-tag-web/src/package.xml, packages/pluggableWidgets/google-tag-web/src/utils.ts
---
Don't suppress sub-sequential "config" commands in the widget.
=> [WC-1897] allowing multiple "config" commands in Google Tag

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/package.xml
---
Don't request total count if infinite scrolling is enabled.
Data grid fetching doesn't request count when set to infinite scrolling. Could be checked by `wantCount` flag in "xas" requests.
=> [WC-1896] don't fetch total count if infinite scrolling is enabled

packages/pluggableWidgets/video-player-web/CHANGELOG.md, packages/pluggableWidgets/video-player-web/cypress/integration/VideoPlayer.spec.js, packages/pluggableWidgets/video-player-web/package.json, packages/pluggableWidgets/video-player-web/src/components/Youtube.tsx, packages/pluggableWidgets/video-player-web/src/components/__tests__/__snapshots__/Youtube.spec.tsx.snap, packages/pluggableWidgets/video-player-web/src/package.xml
Bug fix: Youtube video cannot mute on first load if the setting is set to Mute.
youtube video has different parameters for mute on load,
previously it was "muted=1", changed to "mute=1"
=> fix(video-player): youtube video not mute on load

packages/pluggableWidgets/tree-node-web/CHANGELOG.md, packages/pluggableWidgets/tree-node-web/src/components/TreeNode.tsx
Bug fix: tree node not re-rendered when number of children updated
updated "isActualLeafNode" variables when number of children updated.
=> fix(tree-node): refresh when children updated

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-design-properties.scss
Bug fix: right border not shown if hiding column capabilities disabled.
Try select "no" on hiding column in personalization tab on Datagrid 2.
previously, right border is missing.
this PR will fix it.
=> Wc 1980 dg2 right border issue

packages/pluggableWidgets/maps-web/CHANGELOG.md, packages/pluggableWidgets/maps-web/package.json, packages/pluggableWidgets/maps-web/src/components/LeafletMap.tsx, packages/pluggableWidgets/maps-web/src/package.xml
fix map not pan to centered marker location after zoom.
fix by changing fitToBound with flyToBound to make sure that map is panning to correct marker location after zoom
=> fix: map not centered after zoom

packages/pluggableWidgets/charts-web/CHANGELOG.md, packages/pluggableWidgets/charts-web/package.json, packages/pluggableWidgets/charts-web/src/package.xml
---
Add a note about potential breaking changes.
=> [WC-1999] chore(charts-web): update changelog

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/cypress/integration/DataGrid.spec.js, packages/pluggableWidgets/datagrid-web/cypress/integration/DataGridSelection.spec.js, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/components/ColumnSelector.tsx, packages/pluggableWidgets/datagrid-web/src/components/Table.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/ColumnSelector.spec.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
Bug Fix: this issue relates with previously introduced changed to allow non-numeric ID (fix a11y).
This changes causing "visible column" not working as expected due to the reference with "hidden column" that is still index-based.
Fix by adjusting correct attribute.
=> [WC-2018] fix: column hide by default not working

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-date-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-date-filter-web/package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/components/DatePicker.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/package.xml
Bug fix:
date filter not fully visible on container overflow : scrolls.
fixed by changing popper js mode to `position:fixed` instead of `position:absolute` .
popper js will do the calculation for positioning (tethered to input) automatically.
but overflow will works.
https://popper.js.org/docs/v2/constructors/#strategy
- check if popup goes under topbar ✅ [ with latest atlas-core ]
- check if popup tethered to input when scrolled up✅
- check if popup maintain correct position when datagrid header filter goes into sticky position ✅
=> fix: [WC-2002] datefilter not fully shown on overflow scrolls

packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/helpers/utils.ts
feature (combobox) : add proper text for design mode and page explorer preview
For Association type: Association caption
For Enumeration type: [enumeration, Attribute]
For Boolean type: [boolean, Attribute]
=> feat(combo-box): [WC-2049][WC-2050] Add design mode and page explorer text

packages/pluggableWidgets/image-web/CHANGELOG.md, packages/pluggableWidgets/image-web/src/Image.editorConfig.ts, packages/pluggableWidgets/image-web/src/ui/Image.scss, packages/shared/widget-plugin-platform/src/preview/structure-preview-api.ts
* Added structure mode preview for static and dynamic images (the latter only if they have a static default image)
* Improved the captions in the Page Explorer
* fixed an issue where the size of icons from the new icon collections was not configurable
* fixed an issue where the image would take too much space when placed outside of containers
**Structure preview**
* If you select a static image, it should show in structure mode (Note: in <10.2 it will always default to size 100*100px because of API limitations)
* If you selecta dynamic image and set a static image as a default, it should show the default in structure mode
* Any other selection should render the original fallback image
* Setting a size in pixels should now affect the rendering size of the image on the canvas (if only a …
=> feat(image-web): add structure mode previews & fixes

packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/MultiSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/SingleSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftSingleSelectProps.ts
New Feature:
Allow clicking on container to toggle open/close combobox.
- this is achieved by removing toggle button props from the real toggle button, and move it to the container instead. (toggle button is not focusable anyway)
- click event still propagated down, and allows clear button, input focus, etc to occurs.
- found problem with previous behavior whereas options menu open "on input focus" event, 
- - this is handled by keeping whichever open state currently when "on input focus" event occurs.
=> [WC-2147] open combobox menu on clicking container

packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/MultiSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/SingleSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/components/Placeholder.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationSimpleCaptionsProvider.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/BaseAssociationSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Association/utils.ts, packages/pluggableWidgets/combobox-web/src/helpers/EnumBool/EnumAndBooleanSimpleCaptionsProvider.tsx, packages/pluggableWidgets/combobox-web/src/helpers/EnumBool/EnumBoolSingleSelector.tsx, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/helpers/utils.ts, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftSingleSelectProps.ts, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
New feature:
Add custom content dropzone on combo-box
adding new property:
`optionsSourceAssociationCustomContentType` -> Yes, List Item, No
`optionsSourceAssociationCustomContent` -> widgets
general implementation:
Association-Caption  has to know when to render custom content and normal text, thus the load of figuring out which one to render falls into the caption-renderer.
upon implmentation:
- caption-renderer must know where to render: `type CaptionPlacement = "label" | "options";`
- this placement then matched with `optionsSourceAssociationCustomContentType` property to help caption-renderer figuring out correct component to render
- apparently, custom content must be rendered before input element, this adds logic complexity in SingleSelection, which is solved by using different …
=> [WC-1297]feat(combo-box): Custom content dropzone

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml
Bug fix: Editor not displaying data sometimes.
it seems like there’s a racing condition on updating the editor’s data.
this probably because unsync DOM with React’s component.
we could try debugging more and making a proper fix, but that would require a lot of refactoring.
delaying setData for 50ms seems works for now.
=> fix: inconsistent behavior with editor set data

packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftMultiSelectProps.ts, packages/pluggableWidgets/combobox-web/src/hooks/useDownshiftSingleSelectProps.ts, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
---
Override the default screen reader `getA11yStatusMessage` method inside Downshift to include the selected items in announcement when reading the combobox. 
Now users can modify the a11yStatusMessage which is read by screen readers while using combobox, by changing the default message in the Accessibility tab in SP.
Also, since to this story initially was focusing on Multi selection, we noticed there is a mismatch in behaviour with Single and Multi selection; 
Single selection doesn't open menu when tab focused, but does when click focused. (_correct behaviour_)
Multi selection did open menu both when tab and click focused, so aligned it with Single now.
- Focusing on Multi selection both with tab and …
=> [WC-2151]: Combobox screenreader a11y

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/datagrid-web/src/utils/useShowPagination.ts, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
Data grid 1 has an option "Show paging bar": "No" The Data Grid 2, will always show pagination buttons. This PR will add an extra property for "Showing paging buttons: When necessary"
As a developer/user we do not always need pagination, some use cases will only have a limited number of items, and the paging buttons only confuses the end users, and taking valuable space on the screen.
This is a non breaking change, by adding an extra property with little code change.
The "Showing paging buttons" property is only visible when the  "Pagination" option set to "Button".
=> [WC-2256] DG2 pagination when necessary

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/components/ComboboxMenuWrapper.tsx, packages/pluggableWidgets/combobox-web/src/package.xml
on clicking scrollbar in dropdown menu,
the "related target" is incorrect.
thus, this event is detected as "onBlur" and close the dropdown directly.
prevent the onblur event being called by handling onMouseDown in the menu itself.
=> [WC-2320] fix: dropdown closing when click on scrollbar

packages/pluggableWidgets/html-element-web/CHANGELOG.md, packages/pluggableWidgets/html-element-web/package.json, packages/pluggableWidgets/html-element-web/src/HTMLElement.editorConfig.ts, packages/pluggableWidgets/html-element-web/src/HTMLElement.tsx, packages/pluggableWidgets/html-element-web/src/HTMLElement.xml, packages/pluggableWidgets/html-element-web/src/components/HTMLTag.tsx, packages/pluggableWidgets/html-element-web/src/package.xml, packages/pluggableWidgets/html-element-web/src/utils/props-utils.ts, packages/pluggableWidgets/html-element-web/typings/HTMLElementProps.d.ts
Add **Advanced** tab in the config. Add **Configuration for HTML sanitization** property. This allows specifying additional config as per: https://github.com/cure53/DOMPurify#control-our-allow-lists-and-block-lists
=> [WC-2340] Allow sanitization config in html-element

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/__tests__/__snapshots__/MultiSelection.spec.tsx.snap, packages/pluggableWidgets/combobox-web/src/components/ComboboxMenuWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/SelectAllButton.tsx
---
To prevent menu closing directly on clicking, we previously added event propagate stopper in menu footer click event.
But apparently, this is also stopping element getting focus.
thus, this PR adding focus to each element target clicked on footer click event.
note for testing: please also validate with multi-selection and select all button.
=> [WC-2381] fix: input text does not work in the combobox footer area

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/helpers/state/column/ColumnStore.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
Because of the logic of tracking underlying properties we lost track of the underlying attribute, this resulted in broken sorting for non-attribute columns even if attributes for those columns were selected.
=> [WC-2442] fix sorting for custom content

packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/components/Header.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/Header.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Header.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/src/helpers/state/ColumnGroupStore.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/useRootStore.ts
Make the swap behavior more intuitive. The change involves moving `.dragging` class up the tree from `column-container` to the `.th` level to allow better styling control over the whole cell.
Also included non-functional changes to take care of leftovers from the previous story.
=> [WC-2400] Improve columns swap behavior

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/helpers/state/GridPersonalizationStore.ts, packages/pluggableWidgets/datagrid-web/src/helpers/storage/LocalStoragePersonalizationStorage.ts, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts
It is now possible to select Local storage as a storage option for personalization config.
=> [WC-2216] Allow stroing personalization in localStorage

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx, packages/pluggableWidgets/datagrid-web/src/utils/test-utils.tsx, packages/shared/widget-plugin-grid/src/components/Pagination.tsx
---
When `Show paging buttons` is set to `always`, pagination controls now stay visible even if the DG2 has items shown.
=> [WC-2417]: DG2 show pagination when visibility is set to always

automation/utils/bin/rui-changelog-helper.ts, automation/utils/package.json, automation/utils/src/bump-version.ts, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/helpers/state/ColumnGroupStore.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/ColumnsSortingStore.ts
As we discovered those warnings trigger in a completely valid use case, so it is better to remove them.
=> [WC-2460] Remove useless warnings

packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml, packages/shared/widget-plugin-filtering/src/main.ts, packages/shared/widget-plugin-filtering/src/useDefaultValue.ts
While reading the default value the widget got cached `undefined` while it was still in loading state, hence the default value was missing. This was there for some time, but looks like the re-write of the datagrid widget exposed this bug. Now it should be fixed.
=> [WC-2458] Fix default value in filter widgets

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.tsx, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/StaticSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/__mocks__/intersectionObserverMock.ts, packages/pluggableWidgets/combobox-web/src/components/ComboboxMenuWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/Association/BaseAssociationSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Association/utils.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseOptionsProvider.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseSingleSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/utils.ts, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/helpers/utils.ts, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts, pnpm-lock.yaml
---
Add new property `lazyLoading` for association and database source, with default value set to false.
When set to true, only a set of data is loaded in the beginning, and the rest will be loaded when scrolling to the bottom.
There are no visual changes, all visual changes will be implemented in another PR.
=> [WC-1619]: Combobox lazy load option

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/RichText.editorConfig.ts, packages/pluggableWidgets/rich-text-web/src/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/src/__tests__/RichText.spec.tsx, packages/pluggableWidgets/rich-text-web/src/__tests__/__snapshots__/RichText.spec.tsx.snap, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
---
return back onChange and onKeyPress event that is available on v2.
for consistency, add onChangeType : onLeave or onDataChange
the difference between onchange with onleave changetype is that there is a validation for value change, which makes event triggers only if value change.
as for current on-blur event, it will always trigger regardless of the data.
=> [WC-2480] add missing events from RTE v2

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/Combobox.xml, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/StaticSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/components/ComboboxMenuWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/Loader.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelectionMenu.tsx, packages/pluggableWidgets/combobox-web/src/components/SkeletonLoader.tsx, packages/pluggableWidgets/combobox-web/src/components/SpinnerLoader.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/BaseAssociationSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Association/utils.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseSingleSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/utils.ts, packages/pluggableWidgets/combobox-web/src/helpers/types.ts, packages/pluggableWidgets/combobox-web/src/hooks/useLazyLoading.ts, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts
---
Implement the UI for the lazy load on combobox with the option to select between spinner loader or skeleton loader.
Screenshots:
=> [WC-2455]: Implement Combobox lazy load UI (spinner and skeleton loaders)

packages/pluggableWidgets/slider-web/CHANGELOG.md, packages/pluggableWidgets/slider-web/package.json, packages/pluggableWidgets/slider-web/src/Slider.tsx, packages/pluggableWidgets/slider-web/src/components/Slider.tsx, packages/pluggableWidgets/slider-web/src/package.xml, packages/pluggableWidgets/slider-web/src/utils/createHandleGenerator.tsx
---
Same fix applied in #1118 for `range-slider-web`
Added `getTooltipContainer` method from rc-slider to keep the tooltip in its containing element instead of rendering up in the body.
The tooltip should be following the slider.
=> [WC-2518]: Fix slider-web tooltip positioning

packages/pluggableWidgets/range-slider-web/CHANGELOG.md, packages/pluggableWidgets/range-slider-web/package.json, packages/pluggableWidgets/range-slider-web/src/RangeSlider.tsx, packages/pluggableWidgets/range-slider-web/src/components/RangeSlider.tsx, packages/pluggableWidgets/range-slider-web/src/package.xml, packages/pluggableWidgets/range-slider-web/src/utils/createHandleGenerator.tsx
---
Linked with #1117 
Same as #1117
=> [WC-2518]: Fix range-slider-web tooltip positioning

packages/modules/data-widgets/package.json, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/components/ListItem.tsx, packages/pluggableWidgets/gallery-web/src/features/item-interaction/focus-target-handlers.ts, packages/pluggableWidgets/gallery-web/src/features/item-interaction/item-handlers.ts, packages/pluggableWidgets/gallery-web/src/features/item-interaction/keyboard-utils.ts, packages/pluggableWidgets/gallery-web/src/package.xml
---
Added a new handler method to check if the element is an HTMLInputElement, if so stop the propagation.
Demo project link and #frontend thread:
https://mendix.slack.com/archives/CJZ85RLTA/p1714654971335249
Input elements inside Gallery widget should now be able to use arrow keys to move cursor when focused, but this means where are stopping event propagation for the input elements, which means keyboard navigation behavior for text inputs are going to change.
=> [WC-2474]: Handle keyboard nav for input elements in Gallery

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
We missed an observable on the root level of the component, this made it never re-render when state changed from not loaded to loaded.
=> [WC-2562] Fix rendering issue when visibility expression is has loading state

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/Combobox.editorConfig.ts, packages/pluggableWidgets/combobox-web/src/__tests__/MultiSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/SingleSelection.spec.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/AssociationSimpleCaptionsProvider.tsx, packages/pluggableWidgets/combobox-web/src/helpers/Association/utils.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/utils.ts, packages/pluggableWidgets/combobox-web/src/package.xml
---
it is not possible to filter data if caption on combobox is using expression.
Thus, lazy load is removed for this condition.
We either have to work with an attribute and make search over it or load the whole database
=> [WC-2556] remove lazy load on caption expression

packages/pluggableWidgets/accordion-web/CHANGELOG.md, packages/pluggableWidgets/accordion-web/package.json, packages/pluggableWidgets/accordion-web/src/components/AccordionGroup.tsx, packages/pluggableWidgets/accordion-web/src/components/__tests__/Accordion.spec.tsx, packages/pluggableWidgets/accordion-web/src/components/__tests__/AccordionGroup.spec.tsx, packages/pluggableWidgets/accordion-web/src/package.xml, packages/pluggableWidgets/accordion-web/src/utils/resizeObserver.ts
Bug Fix
---
child content tries to expand, and calculate the content height while parent is not finished expanding. 
thus, child content is still not fully visible, which cause their bounding rectangle calculation incorrect.
fixing this by adding resize observer to the content.
Anything related to accordion content's resizing. make sure the resize observer doesn't try to expand content while content should be collapsing
=> [WC-2511] accordion unsync content display with state

packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/pluggableWidgets/datagrid-text-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-text-filter-web/package.json, packages/pluggableWidgets/datagrid-text-filter-web/src/package.xml, packages/shared/widget-plugin-filter-selector/src/FilterSelector.tsx, packages/shared/widget-plugin-filter-selector/src/__tests__/FilterSelector.spec.tsx, packages/shared/widget-plugin-filtering/src/controls/input/typings.ts, packages/shared/widget-plugin-filtering/src/controls/input/useInputProps.ts
---
When filter is being showed a default filter type is applied via onChange, even though the interaction didn't come from the user. The underlying logic trues to focus the input while it is not needed. This change introduces a flag to let the underlying logic know if the interaction came from the user.
=> [WC-2500] Don't automatically focus the input on default filter type change

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx
---
timer never cleared.
it keeps on creating new instance on datasource update.
this PR fix it.
=> [WC-2637]: Fix: pagination in Data Grid 2 causing extra call in auto refresh

packages/pluggableWidgets/google-tag-web/src/GoogleTag.editorConfig.ts, packages/pluggableWidgets/google-tag-web/src/GoogleTag.tsx, packages/pluggableWidgets/google-tag-web/src/GoogleTag.xml, packages/pluggableWidgets/google-tag-web/typings/GoogleTagProps.d.ts, packages/pluggableWidgets/google-tag-web/typings/global.d.ts
This change introduce a new functionality allowing to optionally share the authenticated user ID with Google Analytics.
Sharing this information allow Google Analytics to identify individual users across different sessions and devices.
This is achieved by modifying the `config` command to add the new `user_id` parameter.
For more details on the feature, please have a look at https://developers.google.com/analytics/devguides/collection/ga4/user-id?client_type=gtag .
=> feat(google-tag-web): send (authenticated) user ID

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/helpers/state/RootGridStore.ts, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/src/stores/RootGalleryStore.ts, packages/shared/widget-plugin-filtering/src/__tests__/condition-utils.spec.ts, packages/shared/widget-plugin-filtering/src/condition-utils.ts
---
Fixed issue with xpath flooding.
=> [WC-2683] Issue with long xpath

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/components/GridHeader.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx, packages/pluggableWidgets/datagrid-web/src/helpers/state/ColumnGroupStore.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/column/ColumnStore.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/datagrid-web/src/utils/test-utils.tsx
Performance improvement
Save personalization settings only at the end pf the resizing, this prevents writing setting multiple times while user is dragging the cursor.
=> [WC-2698] Save new personalized side on resize end

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/features/data-export/useDataExport.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
While switching pages it could happen that the new page is mounted while the old one is not yet unmounted, this led to issue with export controllers not being placed for the new data grids. This change makes it always override the existing controller, but removing a controller on unmount stage only affects own controller.
=> [WC-2737] Fix export to excel issues

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml
---
The issue some customers are facing is when using refresh in client on a microflow in a page with the last version of Datagrid 2 (v2.28). The issue is that when using this microflow on a datagrid to update the data regularly, the loading indicators keep showing up, on every update, and the user simply don't want that. They want the datagrid loading indicator to only show up when doing datasource changes, adding items, or when navigating between pages (paginating).
=> [WC-2752]: fix DG2 refresh in client issue

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/RichText.editorConfig.ts, packages/pluggableWidgets/rich-text-web/src/RichText.tsx, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/src/__tests__/RichText.spec.tsx, packages/pluggableWidgets/rich-text-web/src/__tests__/__snapshots__/RichText.spec.tsx.snap, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/components/EditorWrapper.tsx, packages/pluggableWidgets/rich-text-web/src/package.xml, packages/pluggableWidgets/rich-text-web/src/utils/helpers.ts, packages/pluggableWidgets/rich-text-web/src/utils/themes/mxTheme.ts, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
=> [WC-2745] rich text: multiple feedbacks fix

packages/customWidgets/signature-web/CHANGELOG.md, packages/customWidgets/signature-web/package.json, packages/customWidgets/signature-web/src/components/SignatureContainer.ts, packages/customWidgets/signature-web/src/package.xml
=> fix: Unable to save signature in hybrid apps.

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorConfig.ts, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/__tests__/perf.spec.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/__snapshots__/Table.spec.tsx.snap, packages/pluggableWidgets/datagrid-web/src/utils/useShowPagination.ts, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/shared/widget-plugin-grid/src/components/Pagination.tsx
=> [WC-2757] show numbers of rows pagination for virtual scrolling and load more

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/features/data-export/DSExportRequest.ts
---
Improve export performanc by splitting read in batch operations + calling "get" on all items during read.
Export of small and big table should be enough.
=> [WC-2742] refactor: improve export performance

packages/pluggableWidgets/badge-button-web/src/components/__tests__/BadgeButton.spec.ts, packages/pluggableWidgets/badge-web/src/Badge.editorPreview.tsx, packages/pluggableWidgets/combobox-web/src/__tests__/__mocks__/intersectionObserverMock.ts, packages/pluggableWidgets/heatmap-chart-web/src/HeatMap.editorConfig.ts, packages/pluggableWidgets/rating-web/src/StarRating.editorPreview.tsx, packages/pluggableWidgets/rich-text-web/src/utils/formats/button.ts, packages/pluggableWidgets/rich-text-web/src/utils/helpers.ts, packages/pluggableWidgets/switch-web/src/Switch.editorPreview.tsx, packages/pluggableWidgets/switch-web/src/Switch.tsx, packages/pluggableWidgets/switch-web/src/components/Switch.tsx, packages/pluggableWidgets/time-series-chart-web/src/TimeSeries.editorConfig.ts, packages/pluggableWidgets/timeline-web/src/utils/utils.ts, packages/pluggableWidgets/video-player-web/src/VideoPlayer.editorPreview.tsx
---
Fix lint warnings from widgets, except warnings on react hooks like `useEffect`, `useCallback`...
=> []: Remove lint warnings from pluggable widgets

packages/pluggableWidgets/file-uploader-web/CHANGELOG.md, packages/pluggableWidgets/file-uploader-web/package.json, packages/pluggableWidgets/file-uploader-web/src/FileUploader.xml, packages/pluggableWidgets/file-uploader-web/src/components/FileEntry.tsx, packages/pluggableWidgets/file-uploader-web/src/package.xml, packages/pluggableWidgets/file-uploader-web/src/stores/FileStore.ts, packages/pluggableWidgets/file-uploader-web/src/stores/FileUploaderStore.ts, packages/pluggableWidgets/file-uploader-web/src/utils/predefinedFormats.ts, packages/pluggableWidgets/file-uploader-web/typings/FileUploaderProps.d.ts
Run object creation flow one at a time, not in parallel.
=> [WC-2784] Fix uploading error in file uploader on uncommited objects

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/e2e/DataGrid.spec.js, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/shared/widget-plugin-filtering/src/stores/input/BaseInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/DateInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/NumberInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/StringInputFilterStore.ts
---
When a column is hidden by default, a corresponding filter widget is never mounted and has no way of communicating it's default values to the data grid, and the data grid was assuming the default "equals" filter. Later on, the saved "equal" was overriding the actual value from the filter. To prevent this from happening - don't return value for storage if the filter is not yet properly initialized (as from default value or view state).
=> [WC-2823] Don't save ininitialized filters to the personalization

packages/pluggableWidgets/html-element-web/CHANGELOG.md, packages/pluggableWidgets/html-element-web/package.json, packages/pluggableWidgets/html-element-web/src/package.xml, packages/pluggableWidgets/rich-text-web/package.json, pnpm-lock.yaml
The version 3 is not advertising any breaking changes except dropping support for MSIE, but we don't support it anyway. And we don't need separate typings package anymore 🎉 .
=> [WC-2854] Update DOMPurify dependency

packages/modules/file-uploader/CHANGELOG.md, packages/modules/file-uploader/package.json, packages/pluggableWidgets/file-uploader-web/CHANGELOG.md, packages/pluggableWidgets/file-uploader-web/package.json, packages/pluggableWidgets/file-uploader-web/src/FileUploader.xml, packages/pluggableWidgets/file-uploader-web/src/package.xml
Add defaultValues in XML. Because it is a breaking change, bump version to 10.15.
=> [WC-2610] File Uploader, preconfigured NF

packages/pluggableWidgets/color-picker-web/CHANGELOG.md, packages/pluggableWidgets/color-picker-web/package.json, packages/pluggableWidgets/color-picker-web/rollup.config.js, packages/pluggableWidgets/color-picker-web/src/package.xml
Some external dependencies are not compatible with react client. Reconfigure commonjs plugin in order to fix those issue and convert requires of external deps to imports.
=> [WC-2844] Fix the compatibility with react client for Color Picker

packages/pluggableWidgets/file-uploader-web/CHANGELOG.md, packages/pluggableWidgets/file-uploader-web/src/FileUploader.editorConfig.ts, packages/pluggableWidgets/file-uploader-web/src/FileUploader.xml, packages/pluggableWidgets/file-uploader-web/src/components/ActionButton.tsx, packages/pluggableWidgets/file-uploader-web/src/components/ActionsBar.tsx, packages/pluggableWidgets/file-uploader-web/src/components/FileEntry.tsx, packages/pluggableWidgets/file-uploader-web/src/components/FileUploaderRoot.tsx, packages/pluggableWidgets/file-uploader-web/src/stores/FileStore.ts, packages/pluggableWidgets/file-uploader-web/src/stores/FileUploaderStore.ts, packages/pluggableWidgets/file-uploader-web/src/ui/FileUploader.scss, packages/pluggableWidgets/file-uploader-web/src/utils/DatasourceUpdateProcessor.ts, packages/pluggableWidgets/file-uploader-web/src/utils/__tests__/DatasourceUpdateProcessor.spec.ts, packages/pluggableWidgets/file-uploader-web/typings/FileUploaderProps.d.ts
=> [WC-2859] File uploader custom buttons

packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.xml, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.xml, packages/pluggableWidgets/datagrid-number-filter-web/src/hocs/withLinkedAttributes.tsx, packages/pluggableWidgets/datagrid-number-filter-web/typings/DatagridNumberFilterProps.d.ts, packages/pluggableWidgets/datagrid-text-filter-web/typings/DatagridTextFilterProps.d.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/NumberStoreProvider.ts, packages/shared/widget-plugin-filtering/src/stores/input/NumberInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/StringInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/store-utils.ts
=> [WC-2868] add number filter linked datasource

packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/rollup.config.js, turbo.json
---
Added rollup config for including locales create by create-translation
=> [WC-2723]: Add rollup config for i18n locales (Combobox)

packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.tsx, packages/pluggableWidgets/datagrid-date-filter-web/src/DatagridDateFilter.xml, packages/pluggableWidgets/datagrid-date-filter-web/src/hocs/withDateLinkedAttributes.tsx, packages/pluggableWidgets/datagrid-date-filter-web/typings/DatagridDateFilterProps.d.ts, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/DatagridNumberFilter.xml, packages/pluggableWidgets/datagrid-number-filter-web/src/hocs/withLinkedAttributes.tsx, packages/pluggableWidgets/datagrid-number-filter-web/typings/DatagridNumberFilterProps.d.ts, packages/pluggableWidgets/datagrid-text-filter-web/src/DatagridTextFilter.xml, packages/pluggableWidgets/datagrid-text-filter-web/typings/DatagridTextFilterProps.d.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/BaseStoreProvider.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/DateStoreProvider.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/NumberStoreProvider.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/StringStoreProvider.ts, packages/shared/widget-plugin-filtering/src/stores/input/BaseInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/DateInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/NumberInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/StringInputFilterStore.ts, packages/shared/widget-plugin-filtering/src/stores/input/store-utils.ts, packages/shared/widget-plugin-filtering/src/typings/FilterObserver.ts
=> [WC-2869][WC-2868] improved filtering date time and number

packages/modules/data-widgets/package.json, packages/pluggableWidgets/datagrid-number-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-number-filter-web/package.json, packages/pluggableWidgets/datagrid-number-filter-web/src/components/NumberFilterContainer.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/components/__tests__/DatagridNumberFilter.spec.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/components/__tests__/__snapshots__/DatagridNumberFilter.spec.tsx.snap, packages/pluggableWidgets/datagrid-number-filter-web/src/package.xml, packages/shared/widget-plugin-filtering/src/controllers/NumberFilterController.ts, packages/shared/widget-plugin-filtering/src/controls/input/InputWithFilters.tsx, packages/shared/widget-plugin-filtering/src/stores/InputStore.ts
---
Input of type=number is having build it behavior for number parsing, this messes up with locale-specific number parsing, switch to type=text. 
Bonus: highlight the input in red when number parsing was not successful.
=> [WC-2882] Use text input for number filter (9.24)

packages/pluggableWidgets/calendar-web/src/__tests__/Calendar.spec.tsx, packages/pluggableWidgets/calendar-web/src/__tests__/__snapshots__/Calendar.spec.tsx.snap, packages/pluggableWidgets/document-viewer-web/components/BaseViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/DocxViewer.scss, packages/pluggableWidgets/document-viewer-web/components/DocxViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/ErrorViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/ExcelViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/ImageViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/PDFViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/TextViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/documentRenderer.ts, packages/pluggableWidgets/document-viewer-web/components/index.ts, packages/pluggableWidgets/document-viewer-web/package.json, packages/pluggableWidgets/document-viewer-web/src/DocumentViewer.editorConfig.ts, packages/pluggableWidgets/document-viewer-web/src/DocumentViewer.editorPreview.tsx, packages/pluggableWidgets/document-viewer-web/src/DocumentViewer.tsx, packages/pluggableWidgets/document-viewer-web/src/DocumentViewer.xml, packages/pluggableWidgets/document-viewer-web/store/index.ts, packages/pluggableWidgets/document-viewer-web/typings/DocumentViewerProps.d.ts, packages/pluggableWidgets/document-viewer-web/ui/documentViewer.scss, packages/pluggableWidgets/document-viewer-web/ui/documentViewerIcons.scss, packages/pluggableWidgets/document-viewer-web/utils/dimension.ts, packages/pluggableWidgets/document-viewer-web/utils/helpers.ts, packages/pluggableWidgets/document-viewer-web/utils/useRendererSelector.ts, packages/pluggableWidgets/document-viewer-web/utils/useZoomScale.ts, pnpm-lock.yaml
=> [WC-2910] DocumentViewer

packages/modules/data-widgets/src/themesource/datawidgets/web/_three-state-checkbox.scss, packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/SelectAllButton.tsx, packages/pluggableWidgets/combobox-web/src/package.xml, packages/pluggableWidgets/combobox-web/src/ui/Combobox.scss, packages/shared/widget-plugin-component-kit/src/ThreeStateCheckBox.tsx
Improvement
---
Disable the Select All if there are nothing to select [yet].
=> [WC-2897] Disable Select All if there are no items

packages/pluggableWidgets/rich-text-web/src/RichText.editorConfig.ts
---
Hide `View` and `Table` options when rich text is not in custom or advanced mode.
=> [WC-2915]: add view and tableBetter to toolbar group keys

packages/pluggableWidgets/rich-text-web/package.json, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/components/EditorWrapper.tsx, packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/Dialog.scss, packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/Dialog.tsx, packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/DialogContent.tsx, packages/pluggableWidgets/rich-text-web/src/components/ModalDialog/ViewCodeDialog.tsx, packages/pluggableWidgets/rich-text-web/src/ui/RichText.scss, packages/pluggableWidgets/rich-text-web/src/utils/formats/quill-table-better/quill-table-better.ts, packages/pluggableWidgets/rich-text-web/src/utils/formats/quill-table-better/ui/cell-selection.ts, packages/pluggableWidgets/rich-text-web/src/utils/formats/quill-table-better/ui/table-menus.ts, pnpm-lock.yaml
=> [WC-2915][WC-2850] readonly resize module and fullscreen editor height and add code mirror

packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/components/ColumnSelector.tsx, packages/pluggableWidgets/datagrid-web/src/components/__tests__/ColumnSelector.spec.tsx, packages/pluggableWidgets/datagrid-web/src/consistency-check.ts, packages/pluggableWidgets/datagrid-web/src/package.xml
While this check is still helpful, this check might go wrong in a scenario with
multiple languages involved. Prevent this check from showstopping app from
running by switching this check to a warning.
Also fix warnings in tests.
=> [WC-2902] Move caption error to warning

packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/Gallery.xml, packages/pluggableWidgets/gallery-web/src/components/Gallery.tsx, packages/pluggableWidgets/gallery-web/src/components/ListItem.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/Gallery.spec.tsx, packages/pluggableWidgets/gallery-web/src/components/__tests__/__snapshots__/Gallery.spec.tsx.snap, packages/pluggableWidgets/gallery-web/src/features/item-interaction/get-item-aria-props.ts, packages/pluggableWidgets/gallery-web/src/package.xml, packages/pluggableWidgets/gallery-web/typings/GalleryProps.d.ts
---
Add a new property under Accessibility tab. This is linked to data source, so can be based on the item's data. This text gets assigned to `aria-label` on the focus-able element of each item.
=> [WC-2599] Add item description for Gallery

packages/pluggableWidgets/rich-text-web/CHANGELOG.md, packages/pluggableWidgets/rich-text-web/src/RichText.xml, packages/pluggableWidgets/rich-text-web/src/__tests__/RichText.spec.tsx, packages/pluggableWidgets/rich-text-web/src/components/Editor.tsx, packages/pluggableWidgets/rich-text-web/src/components/EditorWrapper.tsx, packages/pluggableWidgets/rich-text-web/src/components/Toolbar.tsx, packages/pluggableWidgets/rich-text-web/src/utils/formats/fonts.ts, packages/pluggableWidgets/rich-text-web/typings/RichTextProps.d.ts
=> [WC-2914]: add support for custom fonts in RichText widget

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/package.json, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseMultiSelectionSelector.ts, packages/pluggableWidgets/combobox-web/src/helpers/Database/DatabaseSingleSelectionSelector.ts, packages/pluggableWidgets/combobox-web/src/package.xml, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts, packages/shared/widget-plugin-filtering/package.json, packages/shared/widget-plugin-test-utils/package.json, packages/shared/widget-plugin-test-utils/src/builders/SelectionMultiValueBuilder.ts, pnpm-lock.yaml
---
Use keep selection API, if available. This change is backwards compatible with current version, so no min Mendix version bump.
=> [WC-2933] Combobox keep selection if available

packages/pluggableWidgets/calendar-web/rollup.config.mjs, packages/pluggableWidgets/calendar-web/src/Calendar.editorConfig.ts, packages/pluggableWidgets/calendar-web/src/Calendar.editorPreview.tsx, packages/pluggableWidgets/calendar-web/src/__tests__/__snapshots__/Calendar.spec.tsx.snap, packages/pluggableWidgets/calendar-web/src/assets/StructureCalendarDark.svg, packages/pluggableWidgets/calendar-web/src/assets/StructureCalendarLight.svg, packages/pluggableWidgets/calendar-web/src/components/Toolbar.tsx, packages/pluggableWidgets/calendar-web/src/utils/calendar-utils.ts, packages/pluggableWidgets/events-web/src/Events.editorConfig.ts, packages/pluggableWidgets/selection-helper-web/src/SelectionHelper.editorConfig.ts, packages/shared/widget-plugin-platform/src/preview/structure-preview-api.ts
=> [WC-2790]: update design/structure modes on Calendar

packages/pluggableWidgets/calendar-web/src/Calendar.xml, packages/pluggableWidgets/calendar-web/src/__tests__/Calendar.spec.tsx, packages/pluggableWidgets/calendar-web/src/utils/calendar-utils.ts, packages/pluggableWidgets/calendar-web/typings/CalendarProps.d.ts
---
implement new property to control event date range visibility
=> [WC-1293]: Calendar event date visibility

packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery.scss, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml
---
Rely on atlas variables for screen breakpoint sizes.
=> [WC-3003] Use screen breakpoints from variables in gallery

packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery.scss, packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/package.json, packages/pluggableWidgets/gallery-web/src/package.xml
---
Rely on atlas variables for screen breakpoint sizes.
=> [WC-3003] Use screen breakpoints from variables in gallery [2.27]

packages/pluggableWidgets/custom-chart-web/CHANGELOG.md, packages/pluggableWidgets/custom-chart-web/package.json, packages/pluggableWidgets/custom-chart-web/src/utils/utils.spec.ts, packages/pluggableWidgets/custom-chart-web/src/utils/utils.ts
=> [WC-2989]Backport custom chart parsing issue

.gitignore, automation/utils/bin/rui-agent-rules.ts, automation/utils/package.json, docs/requirements/app-flow.md, docs/requirements/backend-structure.md, docs/requirements/frontend-guidelines.md, docs/requirements/implementation-plan.md, docs/requirements/project-requirements-document.md, docs/requirements/tech-stack.md, package.json, turbo.json
=> Project Requirement Documents

packages/pluggableWidgets/custom-chart-web/src/__tests__/__snapshots__/mergeChartProps.spec.ts.snap, packages/pluggableWidgets/custom-chart-web/src/__tests__/mergeChartProps.spec.ts, packages/pluggableWidgets/custom-chart-web/src/controllers/ChartPropsController.ts, packages/pluggableWidgets/custom-chart-web/src/utils/utils.ts, packages/shared/charts/src/helpers/useEditorStore.ts
---
Fix issue with warnings when merging props
=> [WC-2976] fix-warnings

packages/pluggableWidgets/maps-web/CHANGELOG.md, packages/pluggableWidgets/maps-web/src/components/LeafletMap.tsx
---
Using `LeafletMap`, when locations are configured to have both a title and an onclick action, the browser console would log a warning: `unknown listener type: undefined`. For us this was quite annoying because we render 100's of locations.
I resolved this by not adding eventhandlers to the marker when the location has a title.
I'm not sure whether `GoogleMap` also has this issue.
- When a location does not have a title and does not have an onclick action: clicking should do nothing
- When a location has a title, but not an onclick: clicking should open a popup
- When a location does not have a title, but does have an onclick: clicking the location should execute the onclick action
- When a location has a title and an onclick action: …
=> fix: unknown listener type: undefined

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/helpers/LazyLoadProvider.ts
=> [WC-2983]fix: combobox set wrong limit on data status loading

package.json, packages/pluggableWidgets/datagrid-date-filter-web/src/components/__tests__/DatagridDateFilter.spec.tsx, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/hocs/withLinkedRefStore.tsx, packages/pluggableWidgets/datagrid-number-filter-web/src/components/__tests__/DatagridNumberFilter.spec.tsx, packages/pluggableWidgets/datagrid-text-filter-web/src/components/__tests__/DatagridTextFilter.spec.tsx, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/package.json, packages/pluggableWidgets/datagrid-web/src/components/WidgetHeaderContext.tsx, packages/pluggableWidgets/datagrid-web/src/controllers/DatasourceParamsController.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/ColumnGroupStore.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/RootGridStore.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/column/ColumnFilterStore.tsx, packages/pluggableWidgets/datagrid-web/src/package.xml, packages/pluggableWidgets/datagrid-web/src/utils/columns-hash.ts, packages/pluggableWidgets/gallery-web/src/controllers/QueryParamsController.ts, packages/pluggableWidgets/gallery-web/src/stores/GalleryStore.ts, packages/shared/filter-commons/src/__tests__/condition-utils.spec.ts, packages/shared/filter-commons/src/condition-utils.ts, packages/shared/widget-plugin-filtering/src/context.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/BaseStoreProvider.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/DateStoreProvider.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/EnumStoreProvider.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/NumberStoreProvider.ts, packages/shared/widget-plugin-filtering/src/custom-filter-api/StringStoreProvider.ts, packages/shared/widget-plugin-filtering/src/stores/generic/CombinedFilter.ts, packages/shared/widget-plugin-filtering/src/stores/generic/CustomFilterHost.ts, packages/shared/widget-plugin-filtering/src/typings/ConditionWithMeta.ts, packages/shared/widget-plugin-filtering/src/typings/ObservableFilterHost.ts, packages/shared/widget-plugin-filtering/src/utils/fnv-1a-hash.ts, packages/shared/widget-plugin-grid/src/utils/fnv-1a-hash.ts
---
This changes remove metadata stored in XPath
=> [WC-2978] Datagrid: Support OData request on filtering

packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss, packages/pluggableWidgets/datagrid-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-web/src/Datagrid.editorPreview.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.tsx, packages/pluggableWidgets/datagrid-web/src/Datagrid.xml, packages/pluggableWidgets/datagrid-web/src/components/GridBody.tsx, packages/pluggableWidgets/datagrid-web/src/components/RefreshIndicator.tsx, packages/pluggableWidgets/datagrid-web/src/components/Widget.tsx, packages/pluggableWidgets/datagrid-web/src/controllers/DerivedLoaderController.ts, packages/pluggableWidgets/datagrid-web/src/helpers/state/RootGridStore.ts, packages/pluggableWidgets/datagrid-web/src/utils/test-utils.tsx, packages/pluggableWidgets/datagrid-web/typings/DatagridProps.d.ts, packages/shared/widget-plugin-grid/src/__tests__/DatasourceController.spec.ts, packages/shared/widget-plugin-grid/src/__tests__/RefreshController.spec.ts, packages/shared/widget-plugin-grid/src/query/DatasourceController.ts, packages/shared/widget-plugin-grid/src/query/RefreshController.ts, packages/shared/widget-plugin-grid/src/query/query-controller.ts
---
Implement a new property to show a refresh indicator. With the refresh indicator any datasource change triggers the progress bar on top of the Datagrid2.
=> [WC-2838]: Implement RefreshIndicator component on Datagrid 2

automation/run-e2e/lib/update-test-project.mjs, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-dropdown-filter.scss, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml, packages/shared/widget-plugin-dropdown-filter/src/controls/base/OptionsWrapper.tsx, packages/shared/widget-plugin-dropdown-filter/src/controls/picker-primitives.tsx
---
Fix regression with options caption overflow and tooltip. It now shows proper ellipsis and tooltip.
=> [WC-3059] Dropdown filter: title for tooltips and ellipsis overflow

automation/run-e2e/lib/update-test-project.mjs, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-dropdown-filter.scss, packages/pluggableWidgets/datagrid-dropdown-filter-web/CHANGELOG.md, packages/pluggableWidgets/datagrid-dropdown-filter-web/package.json, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/DatagridDropdownFilter.editorConfig.ts, packages/pluggableWidgets/datagrid-dropdown-filter-web/src/package.xml, packages/shared/widget-plugin-filtering/src/controls/base/OptionsWrapper.tsx, packages/shared/widget-plugin-filtering/src/controls/picker-primitives.tsx
=> [WC-3059] Dropdown overflow issue [2.32]

packages/pluggableWidgets/image-web/src/Image.editorConfig.ts, packages/pluggableWidgets/image-web/src/Image.tsx, packages/pluggableWidgets/image-web/src/Image.xml, packages/pluggableWidgets/image-web/src/ui/Image.scss, packages/pluggableWidgets/image-web/src/utils/helpers.ts, packages/pluggableWidgets/image-web/typings/ImageProps.d.ts
---
Added support to configure a `min-height` and or `max-height` for the image when the height unit is set to `auto`
Added the viewport unit (`vh`) while setting the height, min-height and max-height values
- Go to the dimensions tab
- Set a different unit & value for every dimension related to height and test if it works in runtime
=> [WC-2481] Image: Enhance dimension properties

packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery-design-properties.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/design-properties.json, packages/pluggableWidgets/gallery-web/CHANGELOG.md
---
- Introduced a new horizontal divider option for Gallery list items.
- Updated design properties to support horizontal dividers, improving visual separation and customization.
This enhances the Gallery widget’s flexibility for list item styling.
- Set 'horizontal borders' design property to list divider
- Check if this divider is properly displayed
=> [WC-2925] Gallery: Horizontal divider for list items

packages/pluggableWidgets/gallery-web/CHANGELOG.md, packages/pluggableWidgets/gallery-web/src/Gallery.editorPreview.tsx, packages/pluggableWidgets/gallery-web/src/features/useGridPositionsPreview.ts, packages/pluggableWidgets/gallery-web/src/ui/GalleryPreview.scss
---
Fixed an issue where the displayed number of columns in preview mode wouldn't match the configuration
Added functionality where the row count doesn't exceed 3 - in cases where it should because of the column count x page size
Added functionality where the rows of the widget slowly fade out in a vertical gradient
If the rows in no circumstance exceed the count of 3.
Therefore configure a page size and column count which would normally cause the row count to exceed 3.
Test this on al viewports
Test if there is a fade-away gradient overlaying the grid items
=> [WC-3047] Gallery: Improve preview with limited rows and fade out

packages/modules/data-widgets/CHANGELOG.md, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-design-properties.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid-filters.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_datagrid.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_date-picker.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_drop-down-sort.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_export-alert.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery-design-properties.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_gallery.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_refresh-indicator.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/_tree-node-design-properties.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/main.scss, packages/modules/data-widgets/src/themesource/datawidgets/web/variables.scss
---
Consolidated all SCSS variables from individual files into `variables.scss` to eliminate duplicates and create a single source of truth for theming, adding !default flags for easier overrides.
- All data grid components render with correct colors, spacing, and styling
- Filter dropdowns, buttons, and icons display properly
- Hover states, selected states, and focus styles work as expected
- Variables can be overridden using !default mechanism
- CSS custom properties update correctly at runtime
- No duplicate or conflicting styles applied
=> [WC-3052] DataWidget: Styling variables cleanup

packages/pluggableWidgets/switch-web/CHANGELOG.md, packages/pluggableWidgets/switch-web/package.json, packages/pluggableWidgets/switch-web/src/__tests__/Switch.spec.tsx, packages/pluggableWidgets/switch-web/src/__tests__/__snapshots__/Switch.spec.tsx.snap, packages/pluggableWidgets/switch-web/src/components/Switch.tsx, packages/pluggableWidgets/switch-web/src/components/__tests__/Switch.spec.tsx, packages/pluggableWidgets/switch-web/src/package.xml
---
- Added a visually hidden native <input type="checkbox"> to the Switch component for accessibility and label support.
- Ensured the Mendix-rendered label with for attribute toggles the switch as expected.
Related branch: https://github.com/mendix/atlas/pull/269
- If clicking the label toggles the Switch
=> [WC-2552] Switch: Improve consistent toggling with label

packages/pluggableWidgets/document-viewer-web/CHANGELOG.md, packages/pluggableWidgets/document-viewer-web/SiemensMendixDocumentViewer__1.1.1__READMEOSS_2025-09-26__06-59-33.html, packages/pluggableWidgets/document-viewer-web/components/DocxViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/ErrorViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/ExcelViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/PDFViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/TextViewer.tsx, packages/pluggableWidgets/document-viewer-web/components/documentRenderer.ts, packages/pluggableWidgets/document-viewer-web/package.json, packages/pluggableWidgets/document-viewer-web/src/DocumentViewer.xml, packages/pluggableWidgets/document-viewer-web/src/package.xml, packages/pluggableWidgets/document-viewer-web/typings/DocumentViewerProps.d.ts, packages/pluggableWidgets/document-viewer-web/utils/useRendererSelector.ts
=> [WC-3050] allow self hosted pdfjs worker file

packages/pluggableWidgets/dropdown-sort-web/CHANGELOG.md, packages/shared/widget-plugin-sorting/src/helpers/SortStoreProvider.ts, packages/shared/widget-plugin-sorting/src/react/hocs/withLinkedSortStore.tsx, packages/shared/widget-plugin-sorting/src/stores/SortOrderStore.ts
---
Widget didn't take captions into account besides first loading. This change makes the caption re-render if they change by observing them.
=> [WC-3091] Fix issue with not loaded captions in Dropdown sort

packages/pluggableWidgets/combobox-web/CHANGELOG.md, packages/pluggableWidgets/combobox-web/src/components/ComboboxWrapper.tsx, packages/pluggableWidgets/combobox-web/src/components/MultiSelection/MultiSelection.tsx, packages/pluggableWidgets/combobox-web/src/components/SingleSelection/SingleSelection.tsx, packages/pluggableWidgets/combobox-web/src/helpers/utils.ts, packages/pluggableWidgets/combobox-web/typings/ComboboxProps.d.ts, packages/shared/widget-plugin-component-kit/src/Alert.tsx
---
Backport of the fix to combobox for programatically connecting the validation to combobox
Combobox should function as it did before, but for both single selection and multiselection when there's a validation error it should be connected through `aria-describedby` and `aria-invalid` should be `true`. In all other cases these two attributes should not appear.
=> fix: backport fix to combobox validation
